package team.a9043.sign_in_system.mapper;

import java.util.List;

import org.apache.ibatis.annotations.Param;
import team.a9043.sign_in_system.pojo.SisCourse;
import team.a9043.sign_in_system.pojo.SisCourseExample;

public interface SisCourseMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sis_course
     *
     * @mbg.generated Mon Aug 27 13:08:41 CST 2018
     */
    long countByExample(SisCourseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sis_course
     *
     * @mbg.generated Mon Aug 27 13:08:41 CST 2018
     */
    int deleteByExample(SisCourseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sis_course
     *
     * @mbg.generated Mon Aug 27 13:08:41 CST 2018
     */
    int deleteByPrimaryKey(String scId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sis_course
     *
     * @mbg.generated Mon Aug 27 13:08:41 CST 2018
     */
    int insert(SisCourse record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sis_course
     *
     * @mbg.generated Mon Aug 27 13:08:41 CST 2018
     */
    int insertSelective(SisCourse record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sis_course
     *
     * @mbg.generated Mon Aug 27 13:08:41 CST 2018
     */
    List<SisCourse> selectByExample(SisCourseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sis_course
     *
     * @mbg.generated Mon Aug 27 13:08:41 CST 2018
     */
    SisCourse selectByPrimaryKey(String scId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sis_course
     *
     * @mbg.generated Mon Aug 27 13:08:41 CST 2018
     */
    int updateByExampleSelective(@Param("record") SisCourse record, @Param(
        "example") SisCourseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sis_course
     *
     * @mbg.generated Mon Aug 27 13:08:41 CST 2018
     */
    int updateByExample(@Param("record") SisCourse record,
                        @Param("example") SisCourseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sis_course
     *
     * @mbg.generated Mon Aug 27 13:08:41 CST 2018
     */
    int updateByPrimaryKeySelective(SisCourse record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sis_course
     *
     * @mbg.generated Mon Aug 27 13:08:41 CST 2018
     */
    int updateByPrimaryKey(SisCourse record);

    int insertList(@Param("sisCourseList") List<SisCourse> sisCourseList);

    int updateNeedMonitorList(@Param("sisCourseList") List<SisCourse> sisCourseList);
}