package team.a9043.sign_in_system.mapper;

import java.util.List;

import org.apache.ibatis.annotations.Param;
import team.a9043.sign_in_system.pojo.SisJoinDepart;
import team.a9043.sign_in_system.pojo.SisJoinDepartExample;

public interface SisJoinDepartMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sis_join_depart
     *
     * @mbg.generated Sat Sep 01 22:13:45 CST 2018
     */
    long countByExample(SisJoinDepartExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sis_join_depart
     *
     * @mbg.generated Sat Sep 01 22:13:45 CST 2018
     */
    int deleteByExample(SisJoinDepartExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sis_join_depart
     *
     * @mbg.generated Sat Sep 01 22:13:45 CST 2018
     */
    int deleteByPrimaryKey(Integer sjdId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sis_join_depart
     *
     * @mbg.generated Sat Sep 01 22:13:45 CST 2018
     */
    int insert(SisJoinDepart record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sis_join_depart
     *
     * @mbg.generated Sat Sep 01 22:13:45 CST 2018
     */
    int insertSelective(SisJoinDepart record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sis_join_depart
     *
     * @mbg.generated Sat Sep 01 22:13:45 CST 2018
     */
    List<SisJoinDepart> selectByExample(SisJoinDepartExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sis_join_depart
     *
     * @mbg.generated Sat Sep 01 22:13:45 CST 2018
     */
    SisJoinDepart selectByPrimaryKey(Integer sjdId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sis_join_depart
     *
     * @mbg.generated Sat Sep 01 22:13:45 CST 2018
     */
    int updateByExampleSelective(@Param("record") SisJoinDepart record,
                                 @Param("example") SisJoinDepartExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sis_join_depart
     *
     * @mbg.generated Sat Sep 01 22:13:45 CST 2018
     */
    int updateByExample(@Param("record") SisJoinDepart record, @Param(
        "example") SisJoinDepartExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sis_join_depart
     *
     * @mbg.generated Sat Sep 01 22:13:45 CST 2018
     */
    int updateByPrimaryKeySelective(SisJoinDepart record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sis_join_depart
     *
     * @mbg.generated Sat Sep 01 22:13:45 CST 2018
     */
    int updateByPrimaryKey(SisJoinDepart record);

    int insertList(@Param("sisJoinDepartList") List<SisJoinDepart> sisJoinDepartList);
}