package team.a9043.sign_in_system.mapper;

import org.apache.ibatis.annotations.Param;
import team.a9043.sign_in_system.pojo.SisJoinCourse;
import team.a9043.sign_in_system.pojo.SisJoinCourseExample;

import java.util.List;

public interface SisJoinCourseMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sis_join_course
     *
     * @mbg.generated Mon Aug 27 13:08:41 CST 2018
     */
    long countByExample(SisJoinCourseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sis_join_course
     *
     * @mbg.generated Mon Aug 27 13:08:41 CST 2018
     */
    int deleteByExample(SisJoinCourseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sis_join_course
     *
     * @mbg.generated Mon Aug 27 13:08:41 CST 2018
     */
    int deleteByPrimaryKey(Integer sjcId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sis_join_course
     *
     * @mbg.generated Mon Aug 27 13:08:41 CST 2018
     */
    int insert(SisJoinCourse record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sis_join_course
     *
     * @mbg.generated Mon Aug 27 13:08:41 CST 2018
     */
    int insertSelective(SisJoinCourse record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sis_join_course
     *
     * @mbg.generated Mon Aug 27 13:08:41 CST 2018
     */
    List<SisJoinCourse> selectByExample(SisJoinCourseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sis_join_course
     *
     * @mbg.generated Mon Aug 27 13:08:41 CST 2018
     */
    SisJoinCourse selectByPrimaryKey(Integer sjcId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sis_join_course
     *
     * @mbg.generated Mon Aug 27 13:08:41 CST 2018
     */
    int updateByExampleSelective(@Param("record") SisJoinCourse record,
                                 @Param("example") SisJoinCourseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sis_join_course
     *
     * @mbg.generated Mon Aug 27 13:08:41 CST 2018
     */
    int updateByExample(@Param("record") SisJoinCourse record, @Param(
        "example") SisJoinCourseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sis_join_course
     *
     * @mbg.generated Mon Aug 27 13:08:41 CST 2018
     */
    int updateByPrimaryKeySelective(SisJoinCourse record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sis_join_course
     *
     * @mbg.generated Mon Aug 27 13:08:41 CST 2018
     */
    int updateByPrimaryKey(SisJoinCourse record);

    int insertList(@Param("sisJoinCourseList") List<SisJoinCourse> sisJoinCourseList);
}