package team.a9043.sign_in_system.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import team.a9043.sign_in_system.pojo.SisMonitorTrans;
import team.a9043.sign_in_system.pojo.SisMonitorTransExample;
import team.a9043.sign_in_system.pojo.SisMonitorTransKey;

public interface SisMonitorTransMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sis_monitor_trans
     *
     * @mbg.generated Tue Aug 28 21:51:04 CST 2018
     */
    long countByExample(SisMonitorTransExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sis_monitor_trans
     *
     * @mbg.generated Tue Aug 28 21:51:04 CST 2018
     */
    int deleteByExample(SisMonitorTransExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sis_monitor_trans
     *
     * @mbg.generated Tue Aug 28 21:51:04 CST 2018
     */
    int deleteByPrimaryKey(SisMonitorTransKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sis_monitor_trans
     *
     * @mbg.generated Tue Aug 28 21:51:04 CST 2018
     */
    int insert(SisMonitorTrans record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sis_monitor_trans
     *
     * @mbg.generated Tue Aug 28 21:51:04 CST 2018
     */
    int insertSelective(SisMonitorTrans record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sis_monitor_trans
     *
     * @mbg.generated Tue Aug 28 21:51:04 CST 2018
     */
    List<SisMonitorTrans> selectByExample(SisMonitorTransExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sis_monitor_trans
     *
     * @mbg.generated Tue Aug 28 21:51:04 CST 2018
     */
    SisMonitorTrans selectByPrimaryKey(SisMonitorTransKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sis_monitor_trans
     *
     * @mbg.generated Tue Aug 28 21:51:04 CST 2018
     */
    int updateByExampleSelective(@Param("record") SisMonitorTrans record, @Param("example") SisMonitorTransExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sis_monitor_trans
     *
     * @mbg.generated Tue Aug 28 21:51:04 CST 2018
     */
    int updateByExample(@Param("record") SisMonitorTrans record, @Param("example") SisMonitorTransExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sis_monitor_trans
     *
     * @mbg.generated Tue Aug 28 21:51:04 CST 2018
     */
    int updateByPrimaryKeySelective(SisMonitorTrans record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sis_monitor_trans
     *
     * @mbg.generated Tue Aug 28 21:51:04 CST 2018
     */
    int updateByPrimaryKey(SisMonitorTrans record);
}