package team.a9043.sign_in_system.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import team.a9043.sign_in_system.pojo.SisRole;
import team.a9043.sign_in_system.pojo.SisRoleExample;

public interface SisRoleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sis_role
     *
     * @mbg.generated Mon Aug 27 13:08:41 CST 2018
     */
    long countByExample(SisRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sis_role
     *
     * @mbg.generated Mon Aug 27 13:08:41 CST 2018
     */
    int deleteByExample(SisRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sis_role
     *
     * @mbg.generated Mon Aug 27 13:08:41 CST 2018
     */
    int deleteByPrimaryKey(Integer srId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sis_role
     *
     * @mbg.generated Mon Aug 27 13:08:41 CST 2018
     */
    int insert(SisRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sis_role
     *
     * @mbg.generated Mon Aug 27 13:08:41 CST 2018
     */
    int insertSelective(SisRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sis_role
     *
     * @mbg.generated Mon Aug 27 13:08:41 CST 2018
     */
    List<SisRole> selectByExample(SisRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sis_role
     *
     * @mbg.generated Mon Aug 27 13:08:41 CST 2018
     */
    SisRole selectByPrimaryKey(Integer srId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sis_role
     *
     * @mbg.generated Mon Aug 27 13:08:41 CST 2018
     */
    int updateByExampleSelective(@Param("record") SisRole record, @Param("example") SisRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sis_role
     *
     * @mbg.generated Mon Aug 27 13:08:41 CST 2018
     */
    int updateByExample(@Param("record") SisRole record, @Param("example") SisRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sis_role
     *
     * @mbg.generated Mon Aug 27 13:08:41 CST 2018
     */
    int updateByPrimaryKeySelective(SisRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sis_role
     *
     * @mbg.generated Mon Aug 27 13:08:41 CST 2018
     */
    int updateByPrimaryKey(SisRole record);
}