package team.a9043.sign_in_system.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import team.a9043.sign_in_system.pojo.SisSignInDetail;
import team.a9043.sign_in_system.pojo.SisSignInDetailExample;

public interface SisSignInDetailMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sis_sign_in_detail
     *
     * @mbg.generated Tue Nov 06 20:55:06 CST 2018
     */
    long countByExample(SisSignInDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sis_sign_in_detail
     *
     * @mbg.generated Tue Nov 06 20:55:06 CST 2018
     */
    int deleteByExample(SisSignInDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sis_sign_in_detail
     *
     * @mbg.generated Tue Nov 06 20:55:06 CST 2018
     */
    int deleteByPrimaryKey(Integer ssidId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sis_sign_in_detail
     *
     * @mbg.generated Tue Nov 06 20:55:06 CST 2018
     */
    int insert(SisSignInDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sis_sign_in_detail
     *
     * @mbg.generated Tue Nov 06 20:55:06 CST 2018
     */
    int insertSelective(SisSignInDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sis_sign_in_detail
     *
     * @mbg.generated Tue Nov 06 20:55:06 CST 2018
     */
    List<SisSignInDetail> selectByExampleWithBLOBs(SisSignInDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sis_sign_in_detail
     *
     * @mbg.generated Tue Nov 06 20:55:06 CST 2018
     */
    List<SisSignInDetail> selectByExample(SisSignInDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sis_sign_in_detail
     *
     * @mbg.generated Tue Nov 06 20:55:06 CST 2018
     */
    SisSignInDetail selectByPrimaryKey(Integer ssidId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sis_sign_in_detail
     *
     * @mbg.generated Tue Nov 06 20:55:06 CST 2018
     */
    int updateByExampleSelective(@Param("record") SisSignInDetail record, @Param("example") SisSignInDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sis_sign_in_detail
     *
     * @mbg.generated Tue Nov 06 20:55:06 CST 2018
     */
    int updateByExampleWithBLOBs(@Param("record") SisSignInDetail record, @Param("example") SisSignInDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sis_sign_in_detail
     *
     * @mbg.generated Tue Nov 06 20:55:06 CST 2018
     */
    int updateByExample(@Param("record") SisSignInDetail record, @Param("example") SisSignInDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sis_sign_in_detail
     *
     * @mbg.generated Tue Nov 06 20:55:06 CST 2018
     */
    int updateByPrimaryKeySelective(SisSignInDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sis_sign_in_detail
     *
     * @mbg.generated Tue Nov 06 20:55:06 CST 2018
     */
    int updateByPrimaryKeyWithBLOBs(SisSignInDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sis_sign_in_detail
     *
     * @mbg.generated Tue Nov 06 20:55:06 CST 2018
     */
    int updateByPrimaryKey(SisSignInDetail record);

    int insertList(@Param("sisSignInDetailList") List<SisSignInDetail> sisSignInDetailList);

    int updateList(@Param("sisSignInDetailList") List<SisSignInDetail> sisSignInDetailList);
}