package team.a9043.sign_in_system.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import team.a9043.sign_in_system.pojo.SisSchedule;
import team.a9043.sign_in_system.pojo.SisScheduleExample;

public interface SisScheduleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sis_schedule
     *
     * @mbg.generated Wed Sep 19 17:25:34 CST 2018
     */
    long countByExample(SisScheduleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sis_schedule
     *
     * @mbg.generated Wed Sep 19 17:25:34 CST 2018
     */
    int deleteByExample(SisScheduleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sis_schedule
     *
     * @mbg.generated Wed Sep 19 17:25:34 CST 2018
     */
    int deleteByPrimaryKey(Integer ssId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sis_schedule
     *
     * @mbg.generated Wed Sep 19 17:25:34 CST 2018
     */
    int insert(SisSchedule record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sis_schedule
     *
     * @mbg.generated Wed Sep 19 17:25:34 CST 2018
     */
    int insertSelective(SisSchedule record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sis_schedule
     *
     * @mbg.generated Wed Sep 19 17:25:34 CST 2018
     */
    List<SisSchedule> selectByExample(SisScheduleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sis_schedule
     *
     * @mbg.generated Wed Sep 19 17:25:34 CST 2018
     */
    SisSchedule selectByPrimaryKey(Integer ssId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sis_schedule
     *
     * @mbg.generated Wed Sep 19 17:25:34 CST 2018
     */
    int updateByExampleSelective(@Param("record") SisSchedule record, @Param("example") SisScheduleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sis_schedule
     *
     * @mbg.generated Wed Sep 19 17:25:34 CST 2018
     */
    int updateByExample(@Param("record") SisSchedule record, @Param("example") SisScheduleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sis_schedule
     *
     * @mbg.generated Wed Sep 19 17:25:34 CST 2018
     */
    int updateByPrimaryKeySelective(SisSchedule record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sis_schedule
     *
     * @mbg.generated Wed Sep 19 17:25:34 CST 2018
     */
    int updateByPrimaryKey(SisSchedule record);

    int insertList(@Param("sisScheduleList") List<SisSchedule> sisScheduleList);
}