package team.a9043.sign_in_system.pojo;

public class SisDepartment {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sis_department.sd_id
     *
     * @mbg.generated Sat Sep 01 22:13:45 CST 2018
     */
    private Integer sdId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sis_department.sd_name
     *
     * @mbg.generated Sat Sep 01 22:13:45 CST 2018
     */
    private String sdName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sis_department.sd_id
     *
     * @return the value of sis_department.sd_id
     *
     * @mbg.generated Sat Sep 01 22:13:45 CST 2018
     */
    public Integer getSdId() {
        return sdId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sis_department.sd_id
     *
     * @param sdId the value for sis_department.sd_id
     *
     * @mbg.generated Sat Sep 01 22:13:45 CST 2018
     */
    public void setSdId(Integer sdId) {
        this.sdId = sdId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sis_department.sd_name
     *
     * @return the value of sis_department.sd_name
     *
     * @mbg.generated Sat Sep 01 22:13:45 CST 2018
     */
    public String getSdName() {
        return sdName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sis_department.sd_name
     *
     * @param sdName the value for sis_department.sd_name
     *
     * @mbg.generated Sat Sep 01 22:13:45 CST 2018
     */
    public void setSdName(String sdName) {
        this.sdName = sdName == null ? null : sdName.trim();
    }
}