package team.a9043.sign_in_system.pojo;

import java.util.ArrayList;
import java.util.List;

public class SisJoinCourseExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sis_join_course
     *
     * @mbg.generated Mon Aug 27 13:08:41 CST 2018
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sis_join_course
     *
     * @mbg.generated Mon Aug 27 13:08:41 CST 2018
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sis_join_course
     *
     * @mbg.generated Mon Aug 27 13:08:41 CST 2018
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sis_join_course
     *
     * @mbg.generated Mon Aug 27 13:08:41 CST 2018
     */
    public SisJoinCourseExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sis_join_course
     *
     * @mbg.generated Mon Aug 27 13:08:41 CST 2018
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sis_join_course
     *
     * @mbg.generated Mon Aug 27 13:08:41 CST 2018
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sis_join_course
     *
     * @mbg.generated Mon Aug 27 13:08:41 CST 2018
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sis_join_course
     *
     * @mbg.generated Mon Aug 27 13:08:41 CST 2018
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sis_join_course
     *
     * @mbg.generated Mon Aug 27 13:08:41 CST 2018
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sis_join_course
     *
     * @mbg.generated Mon Aug 27 13:08:41 CST 2018
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sis_join_course
     *
     * @mbg.generated Mon Aug 27 13:08:41 CST 2018
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sis_join_course
     *
     * @mbg.generated Mon Aug 27 13:08:41 CST 2018
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sis_join_course
     *
     * @mbg.generated Mon Aug 27 13:08:41 CST 2018
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sis_join_course
     *
     * @mbg.generated Mon Aug 27 13:08:41 CST 2018
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table sis_join_course
     *
     * @mbg.generated Mon Aug 27 13:08:41 CST 2018
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andSjcIdIsNull() {
            addCriterion("sjc_id is null");
            return (Criteria) this;
        }

        public Criteria andSjcIdIsNotNull() {
            addCriterion("sjc_id is not null");
            return (Criteria) this;
        }

        public Criteria andSjcIdEqualTo(Integer value) {
            addCriterion("sjc_id =", value, "sjcId");
            return (Criteria) this;
        }

        public Criteria andSjcIdNotEqualTo(Integer value) {
            addCriterion("sjc_id <>", value, "sjcId");
            return (Criteria) this;
        }

        public Criteria andSjcIdGreaterThan(Integer value) {
            addCriterion("sjc_id >", value, "sjcId");
            return (Criteria) this;
        }

        public Criteria andSjcIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("sjc_id >=", value, "sjcId");
            return (Criteria) this;
        }

        public Criteria andSjcIdLessThan(Integer value) {
            addCriterion("sjc_id <", value, "sjcId");
            return (Criteria) this;
        }

        public Criteria andSjcIdLessThanOrEqualTo(Integer value) {
            addCriterion("sjc_id <=", value, "sjcId");
            return (Criteria) this;
        }

        public Criteria andSjcIdIn(List<Integer> values) {
            addCriterion("sjc_id in", values, "sjcId");
            return (Criteria) this;
        }

        public Criteria andSjcIdNotIn(List<Integer> values) {
            addCriterion("sjc_id not in", values, "sjcId");
            return (Criteria) this;
        }

        public Criteria andSjcIdBetween(Integer value1, Integer value2) {
            addCriterion("sjc_id between", value1, value2, "sjcId");
            return (Criteria) this;
        }

        public Criteria andSjcIdNotBetween(Integer value1, Integer value2) {
            addCriterion("sjc_id not between", value1, value2, "sjcId");
            return (Criteria) this;
        }

        public Criteria andJoinCourseTypeIsNull() {
            addCriterion("join_course_type is null");
            return (Criteria) this;
        }

        public Criteria andJoinCourseTypeIsNotNull() {
            addCriterion("join_course_type is not null");
            return (Criteria) this;
        }

        public Criteria andJoinCourseTypeEqualTo(Integer value) {
            addCriterion("join_course_type =", value, "joinCourseType");
            return (Criteria) this;
        }

        public Criteria andJoinCourseTypeNotEqualTo(Integer value) {
            addCriterion("join_course_type <>", value, "joinCourseType");
            return (Criteria) this;
        }

        public Criteria andJoinCourseTypeGreaterThan(Integer value) {
            addCriterion("join_course_type >", value, "joinCourseType");
            return (Criteria) this;
        }

        public Criteria andJoinCourseTypeGreaterThanOrEqualTo(Integer value) {
            addCriterion("join_course_type >=", value, "joinCourseType");
            return (Criteria) this;
        }

        public Criteria andJoinCourseTypeLessThan(Integer value) {
            addCriterion("join_course_type <", value, "joinCourseType");
            return (Criteria) this;
        }

        public Criteria andJoinCourseTypeLessThanOrEqualTo(Integer value) {
            addCriterion("join_course_type <=", value, "joinCourseType");
            return (Criteria) this;
        }

        public Criteria andJoinCourseTypeIn(List<Integer> values) {
            addCriterion("join_course_type in", values, "joinCourseType");
            return (Criteria) this;
        }

        public Criteria andJoinCourseTypeNotIn(List<Integer> values) {
            addCriterion("join_course_type not in", values, "joinCourseType");
            return (Criteria) this;
        }

        public Criteria andJoinCourseTypeBetween(Integer value1, Integer value2) {
            addCriterion("join_course_type between", value1, value2, "joinCourseType");
            return (Criteria) this;
        }

        public Criteria andJoinCourseTypeNotBetween(Integer value1, Integer value2) {
            addCriterion("join_course_type not between", value1, value2, "joinCourseType");
            return (Criteria) this;
        }

        public Criteria andScIdIsNull() {
            addCriterion("sc_id is null");
            return (Criteria) this;
        }

        public Criteria andScIdIsNotNull() {
            addCriterion("sc_id is not null");
            return (Criteria) this;
        }

        public Criteria andScIdEqualTo(String value) {
            addCriterion("sc_id =", value, "scId");
            return (Criteria) this;
        }

        public Criteria andScIdNotEqualTo(String value) {
            addCriterion("sc_id <>", value, "scId");
            return (Criteria) this;
        }

        public Criteria andScIdGreaterThan(String value) {
            addCriterion("sc_id >", value, "scId");
            return (Criteria) this;
        }

        public Criteria andScIdGreaterThanOrEqualTo(String value) {
            addCriterion("sc_id >=", value, "scId");
            return (Criteria) this;
        }

        public Criteria andScIdLessThan(String value) {
            addCriterion("sc_id <", value, "scId");
            return (Criteria) this;
        }

        public Criteria andScIdLessThanOrEqualTo(String value) {
            addCriterion("sc_id <=", value, "scId");
            return (Criteria) this;
        }

        public Criteria andScIdLike(String value) {
            addCriterion("sc_id like", value, "scId");
            return (Criteria) this;
        }

        public Criteria andScIdNotLike(String value) {
            addCriterion("sc_id not like", value, "scId");
            return (Criteria) this;
        }

        public Criteria andScIdIn(List<String> values) {
            addCriterion("sc_id in", values, "scId");
            return (Criteria) this;
        }

        public Criteria andScIdNotIn(List<String> values) {
            addCriterion("sc_id not in", values, "scId");
            return (Criteria) this;
        }

        public Criteria andScIdBetween(String value1, String value2) {
            addCriterion("sc_id between", value1, value2, "scId");
            return (Criteria) this;
        }

        public Criteria andScIdNotBetween(String value1, String value2) {
            addCriterion("sc_id not between", value1, value2, "scId");
            return (Criteria) this;
        }

        public Criteria andSuIdIsNull() {
            addCriterion("su_id is null");
            return (Criteria) this;
        }

        public Criteria andSuIdIsNotNull() {
            addCriterion("su_id is not null");
            return (Criteria) this;
        }

        public Criteria andSuIdEqualTo(String value) {
            addCriterion("su_id =", value, "suId");
            return (Criteria) this;
        }

        public Criteria andSuIdNotEqualTo(String value) {
            addCriterion("su_id <>", value, "suId");
            return (Criteria) this;
        }

        public Criteria andSuIdGreaterThan(String value) {
            addCriterion("su_id >", value, "suId");
            return (Criteria) this;
        }

        public Criteria andSuIdGreaterThanOrEqualTo(String value) {
            addCriterion("su_id >=", value, "suId");
            return (Criteria) this;
        }

        public Criteria andSuIdLessThan(String value) {
            addCriterion("su_id <", value, "suId");
            return (Criteria) this;
        }

        public Criteria andSuIdLessThanOrEqualTo(String value) {
            addCriterion("su_id <=", value, "suId");
            return (Criteria) this;
        }

        public Criteria andSuIdLike(String value) {
            addCriterion("su_id like", value, "suId");
            return (Criteria) this;
        }

        public Criteria andSuIdNotLike(String value) {
            addCriterion("su_id not like", value, "suId");
            return (Criteria) this;
        }

        public Criteria andSuIdIn(List<String> values) {
            addCriterion("su_id in", values, "suId");
            return (Criteria) this;
        }

        public Criteria andSuIdNotIn(List<String> values) {
            addCriterion("su_id not in", values, "suId");
            return (Criteria) this;
        }

        public Criteria andSuIdBetween(String value1, String value2) {
            addCriterion("su_id between", value1, value2, "suId");
            return (Criteria) this;
        }

        public Criteria andSuIdNotBetween(String value1, String value2) {
            addCriterion("su_id not between", value1, value2, "suId");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table sis_join_course
     *
     * @mbg.generated do_not_delete_during_merge Mon Aug 27 13:08:41 CST 2018
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table sis_join_course
     *
     * @mbg.generated Mon Aug 27 13:08:41 CST 2018
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}