package team.a9043.sign_in_system.pojo;

public class SisJoinDepart {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sis_join_depart.sjd_id
     *
     * @mbg.generated Sat Sep 01 22:13:45 CST 2018
     */
    private Integer sjdId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sis_join_depart.sc_id
     *
     * @mbg.generated Sat Sep 01 22:13:45 CST 2018
     */
    private String scId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sis_join_depart.sd_id
     *
     * @mbg.generated Sat Sep 01 22:13:45 CST 2018
     */
    private Integer sdId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sis_join_depart.sjd_id
     *
     * @return the value of sis_join_depart.sjd_id
     *
     * @mbg.generated Sat Sep 01 22:13:45 CST 2018
     */
    public Integer getSjdId() {
        return sjdId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sis_join_depart.sjd_id
     *
     * @param sjdId the value for sis_join_depart.sjd_id
     *
     * @mbg.generated Sat Sep 01 22:13:45 CST 2018
     */
    public void setSjdId(Integer sjdId) {
        this.sjdId = sjdId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sis_join_depart.sc_id
     *
     * @return the value of sis_join_depart.sc_id
     *
     * @mbg.generated Sat Sep 01 22:13:45 CST 2018
     */
    public String getScId() {
        return scId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sis_join_depart.sc_id
     *
     * @param scId the value for sis_join_depart.sc_id
     *
     * @mbg.generated Sat Sep 01 22:13:45 CST 2018
     */
    public void setScId(String scId) {
        this.scId = scId == null ? null : scId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sis_join_depart.sd_id
     *
     * @return the value of sis_join_depart.sd_id
     *
     * @mbg.generated Sat Sep 01 22:13:45 CST 2018
     */
    public Integer getSdId() {
        return sdId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sis_join_depart.sd_id
     *
     * @param sdId the value for sis_join_depart.sd_id
     *
     * @mbg.generated Sat Sep 01 22:13:45 CST 2018
     */
    public void setSdId(Integer sdId) {
        this.sdId = sdId;
    }
}