package team.a9043.sign_in_system.pojo;

import org.springframework.lang.NonNull;

public class SisLocation {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sis_location.sl_id
     *
     * @mbg.generated Sat Sep 01 21:38:31 CST 2018
     */
    private Integer slId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sis_location.sl_name
     *
     * @mbg.generated Sat Sep 01 21:38:31 CST 2018
     */
    @NonNull
    private String slName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sis_location.sl_lat
     *
     * @mbg.generated Sat Sep 01 21:38:31 CST 2018
     */
    @NonNull
    private Double slLat;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sis_location.sl_long
     *
     * @mbg.generated Sat Sep 01 21:38:31 CST 2018
     */
    @NonNull
    private Double slLong;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sis_location.sl_id
     *
     * @return the value of sis_location.sl_id
     *
     * @mbg.generated Sat Sep 01 21:38:31 CST 2018
     */
    public Integer getSlId() {
        return slId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sis_location.sl_id
     *
     * @param slId the value for sis_location.sl_id
     *
     * @mbg.generated Sat Sep 01 21:38:31 CST 2018
     */
    public void setSlId(Integer slId) {
        this.slId = slId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sis_location.sl_name
     *
     * @return the value of sis_location.sl_name
     *
     * @mbg.generated Sat Sep 01 21:38:31 CST 2018
     */
    public String getSlName() {
        return slName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sis_location.sl_name
     *
     * @param slName the value for sis_location.sl_name
     *
     * @mbg.generated Sat Sep 01 21:38:31 CST 2018
     */
    public void setSlName(String slName) {
        this.slName = slName == null ? null : slName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sis_location.sl_lat
     *
     * @return the value of sis_location.sl_lat
     *
     * @mbg.generated Sat Sep 01 21:38:31 CST 2018
     */
    public Double getSlLat() {
        return slLat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sis_location.sl_lat
     *
     * @param slLat the value for sis_location.sl_lat
     *
     * @mbg.generated Sat Sep 01 21:38:31 CST 2018
     */
    public void setSlLat(Double slLat) {
        this.slLat = slLat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sis_location.sl_long
     *
     * @return the value of sis_location.sl_long
     *
     * @mbg.generated Sat Sep 01 21:38:31 CST 2018
     */
    public Double getSlLong() {
        return slLong;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sis_location.sl_long
     *
     * @param slLong the value for sis_location.sl_long
     *
     * @mbg.generated Sat Sep 01 21:38:31 CST 2018
     */
    public void setSlLong(Double slLong) {
        this.slLong = slLong;
    }
}