package team.a9043.sign_in_system.pojo;

import java.util.ArrayList;
import java.util.List;

public class SisLocationExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sis_location
     *
     * @mbg.generated Sat Sep 01 21:38:31 CST 2018
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sis_location
     *
     * @mbg.generated Sat Sep 01 21:38:31 CST 2018
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sis_location
     *
     * @mbg.generated Sat Sep 01 21:38:31 CST 2018
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sis_location
     *
     * @mbg.generated Sat Sep 01 21:38:31 CST 2018
     */
    public SisLocationExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sis_location
     *
     * @mbg.generated Sat Sep 01 21:38:31 CST 2018
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sis_location
     *
     * @mbg.generated Sat Sep 01 21:38:31 CST 2018
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sis_location
     *
     * @mbg.generated Sat Sep 01 21:38:31 CST 2018
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sis_location
     *
     * @mbg.generated Sat Sep 01 21:38:31 CST 2018
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sis_location
     *
     * @mbg.generated Sat Sep 01 21:38:31 CST 2018
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sis_location
     *
     * @mbg.generated Sat Sep 01 21:38:31 CST 2018
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sis_location
     *
     * @mbg.generated Sat Sep 01 21:38:31 CST 2018
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sis_location
     *
     * @mbg.generated Sat Sep 01 21:38:31 CST 2018
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sis_location
     *
     * @mbg.generated Sat Sep 01 21:38:31 CST 2018
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sis_location
     *
     * @mbg.generated Sat Sep 01 21:38:31 CST 2018
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table sis_location
     *
     * @mbg.generated Sat Sep 01 21:38:31 CST 2018
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andSlIdIsNull() {
            addCriterion("sl_id is null");
            return (Criteria) this;
        }

        public Criteria andSlIdIsNotNull() {
            addCriterion("sl_id is not null");
            return (Criteria) this;
        }

        public Criteria andSlIdEqualTo(Integer value) {
            addCriterion("sl_id =", value, "slId");
            return (Criteria) this;
        }

        public Criteria andSlIdNotEqualTo(Integer value) {
            addCriterion("sl_id <>", value, "slId");
            return (Criteria) this;
        }

        public Criteria andSlIdGreaterThan(Integer value) {
            addCriterion("sl_id >", value, "slId");
            return (Criteria) this;
        }

        public Criteria andSlIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("sl_id >=", value, "slId");
            return (Criteria) this;
        }

        public Criteria andSlIdLessThan(Integer value) {
            addCriterion("sl_id <", value, "slId");
            return (Criteria) this;
        }

        public Criteria andSlIdLessThanOrEqualTo(Integer value) {
            addCriterion("sl_id <=", value, "slId");
            return (Criteria) this;
        }

        public Criteria andSlIdIn(List<Integer> values) {
            addCriterion("sl_id in", values, "slId");
            return (Criteria) this;
        }

        public Criteria andSlIdNotIn(List<Integer> values) {
            addCriterion("sl_id not in", values, "slId");
            return (Criteria) this;
        }

        public Criteria andSlIdBetween(Integer value1, Integer value2) {
            addCriterion("sl_id between", value1, value2, "slId");
            return (Criteria) this;
        }

        public Criteria andSlIdNotBetween(Integer value1, Integer value2) {
            addCriterion("sl_id not between", value1, value2, "slId");
            return (Criteria) this;
        }

        public Criteria andSlNameIsNull() {
            addCriterion("sl_name is null");
            return (Criteria) this;
        }

        public Criteria andSlNameIsNotNull() {
            addCriterion("sl_name is not null");
            return (Criteria) this;
        }

        public Criteria andSlNameEqualTo(String value) {
            addCriterion("sl_name =", value, "slName");
            return (Criteria) this;
        }

        public Criteria andSlNameNotEqualTo(String value) {
            addCriterion("sl_name <>", value, "slName");
            return (Criteria) this;
        }

        public Criteria andSlNameGreaterThan(String value) {
            addCriterion("sl_name >", value, "slName");
            return (Criteria) this;
        }

        public Criteria andSlNameGreaterThanOrEqualTo(String value) {
            addCriterion("sl_name >=", value, "slName");
            return (Criteria) this;
        }

        public Criteria andSlNameLessThan(String value) {
            addCriterion("sl_name <", value, "slName");
            return (Criteria) this;
        }

        public Criteria andSlNameLessThanOrEqualTo(String value) {
            addCriterion("sl_name <=", value, "slName");
            return (Criteria) this;
        }

        public Criteria andSlNameLike(String value) {
            addCriterion("sl_name like", value, "slName");
            return (Criteria) this;
        }

        public Criteria andSlNameNotLike(String value) {
            addCriterion("sl_name not like", value, "slName");
            return (Criteria) this;
        }

        public Criteria andSlNameIn(List<String> values) {
            addCriterion("sl_name in", values, "slName");
            return (Criteria) this;
        }

        public Criteria andSlNameNotIn(List<String> values) {
            addCriterion("sl_name not in", values, "slName");
            return (Criteria) this;
        }

        public Criteria andSlNameBetween(String value1, String value2) {
            addCriterion("sl_name between", value1, value2, "slName");
            return (Criteria) this;
        }

        public Criteria andSlNameNotBetween(String value1, String value2) {
            addCriterion("sl_name not between", value1, value2, "slName");
            return (Criteria) this;
        }

        public Criteria andSlLatIsNull() {
            addCriterion("sl_lat is null");
            return (Criteria) this;
        }

        public Criteria andSlLatIsNotNull() {
            addCriterion("sl_lat is not null");
            return (Criteria) this;
        }

        public Criteria andSlLatEqualTo(Double value) {
            addCriterion("sl_lat =", value, "slLat");
            return (Criteria) this;
        }

        public Criteria andSlLatNotEqualTo(Double value) {
            addCriterion("sl_lat <>", value, "slLat");
            return (Criteria) this;
        }

        public Criteria andSlLatGreaterThan(Double value) {
            addCriterion("sl_lat >", value, "slLat");
            return (Criteria) this;
        }

        public Criteria andSlLatGreaterThanOrEqualTo(Double value) {
            addCriterion("sl_lat >=", value, "slLat");
            return (Criteria) this;
        }

        public Criteria andSlLatLessThan(Double value) {
            addCriterion("sl_lat <", value, "slLat");
            return (Criteria) this;
        }

        public Criteria andSlLatLessThanOrEqualTo(Double value) {
            addCriterion("sl_lat <=", value, "slLat");
            return (Criteria) this;
        }

        public Criteria andSlLatIn(List<Double> values) {
            addCriterion("sl_lat in", values, "slLat");
            return (Criteria) this;
        }

        public Criteria andSlLatNotIn(List<Double> values) {
            addCriterion("sl_lat not in", values, "slLat");
            return (Criteria) this;
        }

        public Criteria andSlLatBetween(Double value1, Double value2) {
            addCriterion("sl_lat between", value1, value2, "slLat");
            return (Criteria) this;
        }

        public Criteria andSlLatNotBetween(Double value1, Double value2) {
            addCriterion("sl_lat not between", value1, value2, "slLat");
            return (Criteria) this;
        }

        public Criteria andSlLongIsNull() {
            addCriterion("sl_long is null");
            return (Criteria) this;
        }

        public Criteria andSlLongIsNotNull() {
            addCriterion("sl_long is not null");
            return (Criteria) this;
        }

        public Criteria andSlLongEqualTo(Double value) {
            addCriterion("sl_long =", value, "slLong");
            return (Criteria) this;
        }

        public Criteria andSlLongNotEqualTo(Double value) {
            addCriterion("sl_long <>", value, "slLong");
            return (Criteria) this;
        }

        public Criteria andSlLongGreaterThan(Double value) {
            addCriterion("sl_long >", value, "slLong");
            return (Criteria) this;
        }

        public Criteria andSlLongGreaterThanOrEqualTo(Double value) {
            addCriterion("sl_long >=", value, "slLong");
            return (Criteria) this;
        }

        public Criteria andSlLongLessThan(Double value) {
            addCriterion("sl_long <", value, "slLong");
            return (Criteria) this;
        }

        public Criteria andSlLongLessThanOrEqualTo(Double value) {
            addCriterion("sl_long <=", value, "slLong");
            return (Criteria) this;
        }

        public Criteria andSlLongIn(List<Double> values) {
            addCriterion("sl_long in", values, "slLong");
            return (Criteria) this;
        }

        public Criteria andSlLongNotIn(List<Double> values) {
            addCriterion("sl_long not in", values, "slLong");
            return (Criteria) this;
        }

        public Criteria andSlLongBetween(Double value1, Double value2) {
            addCriterion("sl_long between", value1, value2, "slLong");
            return (Criteria) this;
        }

        public Criteria andSlLongNotBetween(Double value1, Double value2) {
            addCriterion("sl_long not between", value1, value2, "slLong");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table sis_location
     *
     * @mbg.generated do_not_delete_during_merge Sat Sep 01 21:38:31 CST 2018
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table sis_location
     *
     * @mbg.generated Sat Sep 01 21:38:31 CST 2018
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}