package team.a9043.sign_in_system.pojo;

import io.swagger.annotations.ApiModelProperty;

import javax.validation.constraints.NotNull;

public class SisMonitorTransKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sis_monitor_trans.ss_id
     *
     * @mbg.generated Tue Aug 28 21:51:04 CST 2018
     */
    @ApiModelProperty("排课")
    private Integer ssId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sis_monitor_trans.smt_week
     *
     * @mbg.generated Tue Aug 28 21:51:04 CST 2018
     */
    @ApiModelProperty("转接周")
    @NotNull
    private Integer smtWeek;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sis_monitor_trans.ss_id
     *
     * @return the value of sis_monitor_trans.ss_id
     *
     * @mbg.generated Tue Aug 28 21:51:04 CST 2018
     */
    public Integer getSsId() {
        return ssId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sis_monitor_trans.ss_id
     *
     * @param ssId the value for sis_monitor_trans.ss_id
     *
     * @mbg.generated Tue Aug 28 21:51:04 CST 2018
     */
    public void setSsId(Integer ssId) {
        this.ssId = ssId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sis_monitor_trans.smt_week
     *
     * @return the value of sis_monitor_trans.smt_week
     *
     * @mbg.generated Tue Aug 28 21:51:04 CST 2018
     */
    public Integer getSmtWeek() {
        return smtWeek;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sis_monitor_trans.smt_week
     *
     * @param smtWeek the value for sis_monitor_trans.smt_week
     *
     * @mbg.generated Tue Aug 28 21:51:04 CST 2018
     */
    public void setSmtWeek(Integer smtWeek) {
        this.smtWeek = smtWeek;
    }
}