package team.a9043.sign_in_system.pojo;

import java.util.ArrayList;
import java.util.List;

public class SisSignInDetailExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sis_sign_in_detail
     *
     * @mbg.generated Tue Nov 06 20:55:06 CST 2018
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sis_sign_in_detail
     *
     * @mbg.generated Tue Nov 06 20:55:06 CST 2018
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sis_sign_in_detail
     *
     * @mbg.generated Tue Nov 06 20:55:06 CST 2018
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sis_sign_in_detail
     *
     * @mbg.generated Tue Nov 06 20:55:06 CST 2018
     */
    public SisSignInDetailExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sis_sign_in_detail
     *
     * @mbg.generated Tue Nov 06 20:55:06 CST 2018
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sis_sign_in_detail
     *
     * @mbg.generated Tue Nov 06 20:55:06 CST 2018
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sis_sign_in_detail
     *
     * @mbg.generated Tue Nov 06 20:55:06 CST 2018
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sis_sign_in_detail
     *
     * @mbg.generated Tue Nov 06 20:55:06 CST 2018
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sis_sign_in_detail
     *
     * @mbg.generated Tue Nov 06 20:55:06 CST 2018
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sis_sign_in_detail
     *
     * @mbg.generated Tue Nov 06 20:55:06 CST 2018
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sis_sign_in_detail
     *
     * @mbg.generated Tue Nov 06 20:55:06 CST 2018
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sis_sign_in_detail
     *
     * @mbg.generated Tue Nov 06 20:55:06 CST 2018
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sis_sign_in_detail
     *
     * @mbg.generated Tue Nov 06 20:55:06 CST 2018
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sis_sign_in_detail
     *
     * @mbg.generated Tue Nov 06 20:55:06 CST 2018
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table sis_sign_in_detail
     *
     * @mbg.generated Tue Nov 06 20:55:06 CST 2018
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andSsidIdIsNull() {
            addCriterion("ssid_id is null");
            return (Criteria) this;
        }

        public Criteria andSsidIdIsNotNull() {
            addCriterion("ssid_id is not null");
            return (Criteria) this;
        }

        public Criteria andSsidIdEqualTo(Integer value) {
            addCriterion("ssid_id =", value, "ssidId");
            return (Criteria) this;
        }

        public Criteria andSsidIdNotEqualTo(Integer value) {
            addCriterion("ssid_id <>", value, "ssidId");
            return (Criteria) this;
        }

        public Criteria andSsidIdGreaterThan(Integer value) {
            addCriterion("ssid_id >", value, "ssidId");
            return (Criteria) this;
        }

        public Criteria andSsidIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("ssid_id >=", value, "ssidId");
            return (Criteria) this;
        }

        public Criteria andSsidIdLessThan(Integer value) {
            addCriterion("ssid_id <", value, "ssidId");
            return (Criteria) this;
        }

        public Criteria andSsidIdLessThanOrEqualTo(Integer value) {
            addCriterion("ssid_id <=", value, "ssidId");
            return (Criteria) this;
        }

        public Criteria andSsidIdIn(List<Integer> values) {
            addCriterion("ssid_id in", values, "ssidId");
            return (Criteria) this;
        }

        public Criteria andSsidIdNotIn(List<Integer> values) {
            addCriterion("ssid_id not in", values, "ssidId");
            return (Criteria) this;
        }

        public Criteria andSsidIdBetween(Integer value1, Integer value2) {
            addCriterion("ssid_id between", value1, value2, "ssidId");
            return (Criteria) this;
        }

        public Criteria andSsidIdNotBetween(Integer value1, Integer value2) {
            addCriterion("ssid_id not between", value1, value2, "ssidId");
            return (Criteria) this;
        }

        public Criteria andSsidStatusIsNull() {
            addCriterion("ssid_status is null");
            return (Criteria) this;
        }

        public Criteria andSsidStatusIsNotNull() {
            addCriterion("ssid_status is not null");
            return (Criteria) this;
        }

        public Criteria andSsidStatusEqualTo(Boolean value) {
            addCriterion("ssid_status =", value, "ssidStatus");
            return (Criteria) this;
        }

        public Criteria andSsidStatusNotEqualTo(Boolean value) {
            addCriterion("ssid_status <>", value, "ssidStatus");
            return (Criteria) this;
        }

        public Criteria andSsidStatusGreaterThan(Boolean value) {
            addCriterion("ssid_status >", value, "ssidStatus");
            return (Criteria) this;
        }

        public Criteria andSsidStatusGreaterThanOrEqualTo(Boolean value) {
            addCriterion("ssid_status >=", value, "ssidStatus");
            return (Criteria) this;
        }

        public Criteria andSsidStatusLessThan(Boolean value) {
            addCriterion("ssid_status <", value, "ssidStatus");
            return (Criteria) this;
        }

        public Criteria andSsidStatusLessThanOrEqualTo(Boolean value) {
            addCriterion("ssid_status <=", value, "ssidStatus");
            return (Criteria) this;
        }

        public Criteria andSsidStatusIn(List<Boolean> values) {
            addCriterion("ssid_status in", values, "ssidStatus");
            return (Criteria) this;
        }

        public Criteria andSsidStatusNotIn(List<Boolean> values) {
            addCriterion("ssid_status not in", values, "ssidStatus");
            return (Criteria) this;
        }

        public Criteria andSsidStatusBetween(Boolean value1, Boolean value2) {
            addCriterion("ssid_status between", value1, value2, "ssidStatus");
            return (Criteria) this;
        }

        public Criteria andSsidStatusNotBetween(Boolean value1, Boolean value2) {
            addCriterion("ssid_status not between", value1, value2, "ssidStatus");
            return (Criteria) this;
        }

        public Criteria andSsiIdIsNull() {
            addCriterion("ssi_id is null");
            return (Criteria) this;
        }

        public Criteria andSsiIdIsNotNull() {
            addCriterion("ssi_id is not null");
            return (Criteria) this;
        }

        public Criteria andSsiIdEqualTo(Integer value) {
            addCriterion("ssi_id =", value, "ssiId");
            return (Criteria) this;
        }

        public Criteria andSsiIdNotEqualTo(Integer value) {
            addCriterion("ssi_id <>", value, "ssiId");
            return (Criteria) this;
        }

        public Criteria andSsiIdGreaterThan(Integer value) {
            addCriterion("ssi_id >", value, "ssiId");
            return (Criteria) this;
        }

        public Criteria andSsiIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("ssi_id >=", value, "ssiId");
            return (Criteria) this;
        }

        public Criteria andSsiIdLessThan(Integer value) {
            addCriterion("ssi_id <", value, "ssiId");
            return (Criteria) this;
        }

        public Criteria andSsiIdLessThanOrEqualTo(Integer value) {
            addCriterion("ssi_id <=", value, "ssiId");
            return (Criteria) this;
        }

        public Criteria andSsiIdIn(List<Integer> values) {
            addCriterion("ssi_id in", values, "ssiId");
            return (Criteria) this;
        }

        public Criteria andSsiIdNotIn(List<Integer> values) {
            addCriterion("ssi_id not in", values, "ssiId");
            return (Criteria) this;
        }

        public Criteria andSsiIdBetween(Integer value1, Integer value2) {
            addCriterion("ssi_id between", value1, value2, "ssiId");
            return (Criteria) this;
        }

        public Criteria andSsiIdNotBetween(Integer value1, Integer value2) {
            addCriterion("ssi_id not between", value1, value2, "ssiId");
            return (Criteria) this;
        }

        public Criteria andSuIdIsNull() {
            addCriterion("su_id is null");
            return (Criteria) this;
        }

        public Criteria andSuIdIsNotNull() {
            addCriterion("su_id is not null");
            return (Criteria) this;
        }

        public Criteria andSuIdEqualTo(String value) {
            addCriterion("su_id =", value, "suId");
            return (Criteria) this;
        }

        public Criteria andSuIdNotEqualTo(String value) {
            addCriterion("su_id <>", value, "suId");
            return (Criteria) this;
        }

        public Criteria andSuIdGreaterThan(String value) {
            addCriterion("su_id >", value, "suId");
            return (Criteria) this;
        }

        public Criteria andSuIdGreaterThanOrEqualTo(String value) {
            addCriterion("su_id >=", value, "suId");
            return (Criteria) this;
        }

        public Criteria andSuIdLessThan(String value) {
            addCriterion("su_id <", value, "suId");
            return (Criteria) this;
        }

        public Criteria andSuIdLessThanOrEqualTo(String value) {
            addCriterion("su_id <=", value, "suId");
            return (Criteria) this;
        }

        public Criteria andSuIdLike(String value) {
            addCriterion("su_id like", value, "suId");
            return (Criteria) this;
        }

        public Criteria andSuIdNotLike(String value) {
            addCriterion("su_id not like", value, "suId");
            return (Criteria) this;
        }

        public Criteria andSuIdIn(List<String> values) {
            addCriterion("su_id in", values, "suId");
            return (Criteria) this;
        }

        public Criteria andSuIdNotIn(List<String> values) {
            addCriterion("su_id not in", values, "suId");
            return (Criteria) this;
        }

        public Criteria andSuIdBetween(String value1, String value2) {
            addCriterion("su_id between", value1, value2, "suId");
            return (Criteria) this;
        }

        public Criteria andSuIdNotBetween(String value1, String value2) {
            addCriterion("su_id not between", value1, value2, "suId");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table sis_sign_in_detail
     *
     * @mbg.generated do_not_delete_during_merge Tue Nov 06 20:55:06 CST 2018
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table sis_sign_in_detail
     *
     * @mbg.generated Tue Nov 06 20:55:06 CST 2018
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}