package team.a9043.sign_in_system.pojo;

import java.util.ArrayList;
import java.util.List;

public class SisSupervisionExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sis_supervision
     *
     * @mbg.generated Mon Aug 27 13:08:41 CST 2018
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sis_supervision
     *
     * @mbg.generated Mon Aug 27 13:08:41 CST 2018
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sis_supervision
     *
     * @mbg.generated Mon Aug 27 13:08:41 CST 2018
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sis_supervision
     *
     * @mbg.generated Mon Aug 27 13:08:41 CST 2018
     */
    public SisSupervisionExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sis_supervision
     *
     * @mbg.generated Mon Aug 27 13:08:41 CST 2018
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sis_supervision
     *
     * @mbg.generated Mon Aug 27 13:08:41 CST 2018
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sis_supervision
     *
     * @mbg.generated Mon Aug 27 13:08:41 CST 2018
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sis_supervision
     *
     * @mbg.generated Mon Aug 27 13:08:41 CST 2018
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sis_supervision
     *
     * @mbg.generated Mon Aug 27 13:08:41 CST 2018
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sis_supervision
     *
     * @mbg.generated Mon Aug 27 13:08:41 CST 2018
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sis_supervision
     *
     * @mbg.generated Mon Aug 27 13:08:41 CST 2018
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sis_supervision
     *
     * @mbg.generated Mon Aug 27 13:08:41 CST 2018
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sis_supervision
     *
     * @mbg.generated Mon Aug 27 13:08:41 CST 2018
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sis_supervision
     *
     * @mbg.generated Mon Aug 27 13:08:41 CST 2018
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table sis_supervision
     *
     * @mbg.generated Mon Aug 27 13:08:41 CST 2018
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andSsIdIsNull() {
            addCriterion("ss_id is null");
            return (Criteria) this;
        }

        public Criteria andSsIdIsNotNull() {
            addCriterion("ss_id is not null");
            return (Criteria) this;
        }

        public Criteria andSsIdEqualTo(Integer value) {
            addCriterion("ss_id =", value, "ssId");
            return (Criteria) this;
        }

        public Criteria andSsIdNotEqualTo(Integer value) {
            addCriterion("ss_id <>", value, "ssId");
            return (Criteria) this;
        }

        public Criteria andSsIdGreaterThan(Integer value) {
            addCriterion("ss_id >", value, "ssId");
            return (Criteria) this;
        }

        public Criteria andSsIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("ss_id >=", value, "ssId");
            return (Criteria) this;
        }

        public Criteria andSsIdLessThan(Integer value) {
            addCriterion("ss_id <", value, "ssId");
            return (Criteria) this;
        }

        public Criteria andSsIdLessThanOrEqualTo(Integer value) {
            addCriterion("ss_id <=", value, "ssId");
            return (Criteria) this;
        }

        public Criteria andSsIdIn(List<Integer> values) {
            addCriterion("ss_id in", values, "ssId");
            return (Criteria) this;
        }

        public Criteria andSsIdNotIn(List<Integer> values) {
            addCriterion("ss_id not in", values, "ssId");
            return (Criteria) this;
        }

        public Criteria andSsIdBetween(Integer value1, Integer value2) {
            addCriterion("ss_id between", value1, value2, "ssId");
            return (Criteria) this;
        }

        public Criteria andSsIdNotBetween(Integer value1, Integer value2) {
            addCriterion("ss_id not between", value1, value2, "ssId");
            return (Criteria) this;
        }

        public Criteria andSsvWeekIsNull() {
            addCriterion("ssv_week is null");
            return (Criteria) this;
        }

        public Criteria andSsvWeekIsNotNull() {
            addCriterion("ssv_week is not null");
            return (Criteria) this;
        }

        public Criteria andSsvWeekEqualTo(Integer value) {
            addCriterion("ssv_week =", value, "ssvWeek");
            return (Criteria) this;
        }

        public Criteria andSsvWeekNotEqualTo(Integer value) {
            addCriterion("ssv_week <>", value, "ssvWeek");
            return (Criteria) this;
        }

        public Criteria andSsvWeekGreaterThan(Integer value) {
            addCriterion("ssv_week >", value, "ssvWeek");
            return (Criteria) this;
        }

        public Criteria andSsvWeekGreaterThanOrEqualTo(Integer value) {
            addCriterion("ssv_week >=", value, "ssvWeek");
            return (Criteria) this;
        }

        public Criteria andSsvWeekLessThan(Integer value) {
            addCriterion("ssv_week <", value, "ssvWeek");
            return (Criteria) this;
        }

        public Criteria andSsvWeekLessThanOrEqualTo(Integer value) {
            addCriterion("ssv_week <=", value, "ssvWeek");
            return (Criteria) this;
        }

        public Criteria andSsvWeekIn(List<Integer> values) {
            addCriterion("ssv_week in", values, "ssvWeek");
            return (Criteria) this;
        }

        public Criteria andSsvWeekNotIn(List<Integer> values) {
            addCriterion("ssv_week not in", values, "ssvWeek");
            return (Criteria) this;
        }

        public Criteria andSsvWeekBetween(Integer value1, Integer value2) {
            addCriterion("ssv_week between", value1, value2, "ssvWeek");
            return (Criteria) this;
        }

        public Criteria andSsvWeekNotBetween(Integer value1, Integer value2) {
            addCriterion("ssv_week not between", value1, value2, "ssvWeek");
            return (Criteria) this;
        }

        public Criteria andSsvActualNumIsNull() {
            addCriterion("ssv_actual_num is null");
            return (Criteria) this;
        }

        public Criteria andSsvActualNumIsNotNull() {
            addCriterion("ssv_actual_num is not null");
            return (Criteria) this;
        }

        public Criteria andSsvActualNumEqualTo(Integer value) {
            addCriterion("ssv_actual_num =", value, "ssvActualNum");
            return (Criteria) this;
        }

        public Criteria andSsvActualNumNotEqualTo(Integer value) {
            addCriterion("ssv_actual_num <>", value, "ssvActualNum");
            return (Criteria) this;
        }

        public Criteria andSsvActualNumGreaterThan(Integer value) {
            addCriterion("ssv_actual_num >", value, "ssvActualNum");
            return (Criteria) this;
        }

        public Criteria andSsvActualNumGreaterThanOrEqualTo(Integer value) {
            addCriterion("ssv_actual_num >=", value, "ssvActualNum");
            return (Criteria) this;
        }

        public Criteria andSsvActualNumLessThan(Integer value) {
            addCriterion("ssv_actual_num <", value, "ssvActualNum");
            return (Criteria) this;
        }

        public Criteria andSsvActualNumLessThanOrEqualTo(Integer value) {
            addCriterion("ssv_actual_num <=", value, "ssvActualNum");
            return (Criteria) this;
        }

        public Criteria andSsvActualNumIn(List<Integer> values) {
            addCriterion("ssv_actual_num in", values, "ssvActualNum");
            return (Criteria) this;
        }

        public Criteria andSsvActualNumNotIn(List<Integer> values) {
            addCriterion("ssv_actual_num not in", values, "ssvActualNum");
            return (Criteria) this;
        }

        public Criteria andSsvActualNumBetween(Integer value1, Integer value2) {
            addCriterion("ssv_actual_num between", value1, value2, "ssvActualNum");
            return (Criteria) this;
        }

        public Criteria andSsvActualNumNotBetween(Integer value1, Integer value2) {
            addCriterion("ssv_actual_num not between", value1, value2, "ssvActualNum");
            return (Criteria) this;
        }

        public Criteria andSsvMobileNumIsNull() {
            addCriterion("ssv_mobile_num is null");
            return (Criteria) this;
        }

        public Criteria andSsvMobileNumIsNotNull() {
            addCriterion("ssv_mobile_num is not null");
            return (Criteria) this;
        }

        public Criteria andSsvMobileNumEqualTo(Integer value) {
            addCriterion("ssv_mobile_num =", value, "ssvMobileNum");
            return (Criteria) this;
        }

        public Criteria andSsvMobileNumNotEqualTo(Integer value) {
            addCriterion("ssv_mobile_num <>", value, "ssvMobileNum");
            return (Criteria) this;
        }

        public Criteria andSsvMobileNumGreaterThan(Integer value) {
            addCriterion("ssv_mobile_num >", value, "ssvMobileNum");
            return (Criteria) this;
        }

        public Criteria andSsvMobileNumGreaterThanOrEqualTo(Integer value) {
            addCriterion("ssv_mobile_num >=", value, "ssvMobileNum");
            return (Criteria) this;
        }

        public Criteria andSsvMobileNumLessThan(Integer value) {
            addCriterion("ssv_mobile_num <", value, "ssvMobileNum");
            return (Criteria) this;
        }

        public Criteria andSsvMobileNumLessThanOrEqualTo(Integer value) {
            addCriterion("ssv_mobile_num <=", value, "ssvMobileNum");
            return (Criteria) this;
        }

        public Criteria andSsvMobileNumIn(List<Integer> values) {
            addCriterion("ssv_mobile_num in", values, "ssvMobileNum");
            return (Criteria) this;
        }

        public Criteria andSsvMobileNumNotIn(List<Integer> values) {
            addCriterion("ssv_mobile_num not in", values, "ssvMobileNum");
            return (Criteria) this;
        }

        public Criteria andSsvMobileNumBetween(Integer value1, Integer value2) {
            addCriterion("ssv_mobile_num between", value1, value2, "ssvMobileNum");
            return (Criteria) this;
        }

        public Criteria andSsvMobileNumNotBetween(Integer value1, Integer value2) {
            addCriterion("ssv_mobile_num not between", value1, value2, "ssvMobileNum");
            return (Criteria) this;
        }

        public Criteria andSsvRecInfoIsNull() {
            addCriterion("ssv_rec_info is null");
            return (Criteria) this;
        }

        public Criteria andSsvRecInfoIsNotNull() {
            addCriterion("ssv_rec_info is not null");
            return (Criteria) this;
        }

        public Criteria andSsvRecInfoEqualTo(String value) {
            addCriterion("ssv_rec_info =", value, "ssvRecInfo");
            return (Criteria) this;
        }

        public Criteria andSsvRecInfoNotEqualTo(String value) {
            addCriterion("ssv_rec_info <>", value, "ssvRecInfo");
            return (Criteria) this;
        }

        public Criteria andSsvRecInfoGreaterThan(String value) {
            addCriterion("ssv_rec_info >", value, "ssvRecInfo");
            return (Criteria) this;
        }

        public Criteria andSsvRecInfoGreaterThanOrEqualTo(String value) {
            addCriterion("ssv_rec_info >=", value, "ssvRecInfo");
            return (Criteria) this;
        }

        public Criteria andSsvRecInfoLessThan(String value) {
            addCriterion("ssv_rec_info <", value, "ssvRecInfo");
            return (Criteria) this;
        }

        public Criteria andSsvRecInfoLessThanOrEqualTo(String value) {
            addCriterion("ssv_rec_info <=", value, "ssvRecInfo");
            return (Criteria) this;
        }

        public Criteria andSsvRecInfoLike(String value) {
            addCriterion("ssv_rec_info like", value, "ssvRecInfo");
            return (Criteria) this;
        }

        public Criteria andSsvRecInfoNotLike(String value) {
            addCriterion("ssv_rec_info not like", value, "ssvRecInfo");
            return (Criteria) this;
        }

        public Criteria andSsvRecInfoIn(List<String> values) {
            addCriterion("ssv_rec_info in", values, "ssvRecInfo");
            return (Criteria) this;
        }

        public Criteria andSsvRecInfoNotIn(List<String> values) {
            addCriterion("ssv_rec_info not in", values, "ssvRecInfo");
            return (Criteria) this;
        }

        public Criteria andSsvRecInfoBetween(String value1, String value2) {
            addCriterion("ssv_rec_info between", value1, value2, "ssvRecInfo");
            return (Criteria) this;
        }

        public Criteria andSsvRecInfoNotBetween(String value1, String value2) {
            addCriterion("ssv_rec_info not between", value1, value2, "ssvRecInfo");
            return (Criteria) this;
        }

        public Criteria andSsvSleepNumIsNull() {
            addCriterion("ssv_sleep_num is null");
            return (Criteria) this;
        }

        public Criteria andSsvSleepNumIsNotNull() {
            addCriterion("ssv_sleep_num is not null");
            return (Criteria) this;
        }

        public Criteria andSsvSleepNumEqualTo(Integer value) {
            addCriterion("ssv_sleep_num =", value, "ssvSleepNum");
            return (Criteria) this;
        }

        public Criteria andSsvSleepNumNotEqualTo(Integer value) {
            addCriterion("ssv_sleep_num <>", value, "ssvSleepNum");
            return (Criteria) this;
        }

        public Criteria andSsvSleepNumGreaterThan(Integer value) {
            addCriterion("ssv_sleep_num >", value, "ssvSleepNum");
            return (Criteria) this;
        }

        public Criteria andSsvSleepNumGreaterThanOrEqualTo(Integer value) {
            addCriterion("ssv_sleep_num >=", value, "ssvSleepNum");
            return (Criteria) this;
        }

        public Criteria andSsvSleepNumLessThan(Integer value) {
            addCriterion("ssv_sleep_num <", value, "ssvSleepNum");
            return (Criteria) this;
        }

        public Criteria andSsvSleepNumLessThanOrEqualTo(Integer value) {
            addCriterion("ssv_sleep_num <=", value, "ssvSleepNum");
            return (Criteria) this;
        }

        public Criteria andSsvSleepNumIn(List<Integer> values) {
            addCriterion("ssv_sleep_num in", values, "ssvSleepNum");
            return (Criteria) this;
        }

        public Criteria andSsvSleepNumNotIn(List<Integer> values) {
            addCriterion("ssv_sleep_num not in", values, "ssvSleepNum");
            return (Criteria) this;
        }

        public Criteria andSsvSleepNumBetween(Integer value1, Integer value2) {
            addCriterion("ssv_sleep_num between", value1, value2, "ssvSleepNum");
            return (Criteria) this;
        }

        public Criteria andSsvSleepNumNotBetween(Integer value1, Integer value2) {
            addCriterion("ssv_sleep_num not between", value1, value2, "ssvSleepNum");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table sis_supervision
     *
     * @mbg.generated do_not_delete_during_merge Mon Aug 27 13:08:41 CST 2018
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table sis_supervision
     *
     * @mbg.generated Mon Aug 27 13:08:41 CST 2018
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}