package team.a9043.sign_in_system.pojo;

import java.util.ArrayList;
import java.util.List;

public class SisScheduleExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sis_schedule
     *
     * @mbg.generated Wed Sep 19 17:25:34 CST 2018
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sis_schedule
     *
     * @mbg.generated Wed Sep 19 17:25:34 CST 2018
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sis_schedule
     *
     * @mbg.generated Wed Sep 19 17:25:34 CST 2018
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sis_schedule
     *
     * @mbg.generated Wed Sep 19 17:25:34 CST 2018
     */
    public SisScheduleExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sis_schedule
     *
     * @mbg.generated Wed Sep 19 17:25:34 CST 2018
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sis_schedule
     *
     * @mbg.generated Wed Sep 19 17:25:34 CST 2018
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sis_schedule
     *
     * @mbg.generated Wed Sep 19 17:25:34 CST 2018
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sis_schedule
     *
     * @mbg.generated Wed Sep 19 17:25:34 CST 2018
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sis_schedule
     *
     * @mbg.generated Wed Sep 19 17:25:34 CST 2018
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sis_schedule
     *
     * @mbg.generated Wed Sep 19 17:25:34 CST 2018
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sis_schedule
     *
     * @mbg.generated Wed Sep 19 17:25:34 CST 2018
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sis_schedule
     *
     * @mbg.generated Wed Sep 19 17:25:34 CST 2018
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sis_schedule
     *
     * @mbg.generated Wed Sep 19 17:25:34 CST 2018
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sis_schedule
     *
     * @mbg.generated Wed Sep 19 17:25:34 CST 2018
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table sis_schedule
     *
     * @mbg.generated Wed Sep 19 17:25:34 CST 2018
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andSsIdIsNull() {
            addCriterion("ss_id is null");
            return (Criteria) this;
        }

        public Criteria andSsIdIsNotNull() {
            addCriterion("ss_id is not null");
            return (Criteria) this;
        }

        public Criteria andSsIdEqualTo(Integer value) {
            addCriterion("ss_id =", value, "ssId");
            return (Criteria) this;
        }

        public Criteria andSsIdNotEqualTo(Integer value) {
            addCriterion("ss_id <>", value, "ssId");
            return (Criteria) this;
        }

        public Criteria andSsIdGreaterThan(Integer value) {
            addCriterion("ss_id >", value, "ssId");
            return (Criteria) this;
        }

        public Criteria andSsIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("ss_id >=", value, "ssId");
            return (Criteria) this;
        }

        public Criteria andSsIdLessThan(Integer value) {
            addCriterion("ss_id <", value, "ssId");
            return (Criteria) this;
        }

        public Criteria andSsIdLessThanOrEqualTo(Integer value) {
            addCriterion("ss_id <=", value, "ssId");
            return (Criteria) this;
        }

        public Criteria andSsIdIn(List<Integer> values) {
            addCriterion("ss_id in", values, "ssId");
            return (Criteria) this;
        }

        public Criteria andSsIdNotIn(List<Integer> values) {
            addCriterion("ss_id not in", values, "ssId");
            return (Criteria) this;
        }

        public Criteria andSsIdBetween(Integer value1, Integer value2) {
            addCriterion("ss_id between", value1, value2, "ssId");
            return (Criteria) this;
        }

        public Criteria andSsIdNotBetween(Integer value1, Integer value2) {
            addCriterion("ss_id not between", value1, value2, "ssId");
            return (Criteria) this;
        }

        public Criteria andSsDayOfWeekIsNull() {
            addCriterion("ss_day_of_week is null");
            return (Criteria) this;
        }

        public Criteria andSsDayOfWeekIsNotNull() {
            addCriterion("ss_day_of_week is not null");
            return (Criteria) this;
        }

        public Criteria andSsDayOfWeekEqualTo(Integer value) {
            addCriterion("ss_day_of_week =", value, "ssDayOfWeek");
            return (Criteria) this;
        }

        public Criteria andSsDayOfWeekNotEqualTo(Integer value) {
            addCriterion("ss_day_of_week <>", value, "ssDayOfWeek");
            return (Criteria) this;
        }

        public Criteria andSsDayOfWeekGreaterThan(Integer value) {
            addCriterion("ss_day_of_week >", value, "ssDayOfWeek");
            return (Criteria) this;
        }

        public Criteria andSsDayOfWeekGreaterThanOrEqualTo(Integer value) {
            addCriterion("ss_day_of_week >=", value, "ssDayOfWeek");
            return (Criteria) this;
        }

        public Criteria andSsDayOfWeekLessThan(Integer value) {
            addCriterion("ss_day_of_week <", value, "ssDayOfWeek");
            return (Criteria) this;
        }

        public Criteria andSsDayOfWeekLessThanOrEqualTo(Integer value) {
            addCriterion("ss_day_of_week <=", value, "ssDayOfWeek");
            return (Criteria) this;
        }

        public Criteria andSsDayOfWeekIn(List<Integer> values) {
            addCriterion("ss_day_of_week in", values, "ssDayOfWeek");
            return (Criteria) this;
        }

        public Criteria andSsDayOfWeekNotIn(List<Integer> values) {
            addCriterion("ss_day_of_week not in", values, "ssDayOfWeek");
            return (Criteria) this;
        }

        public Criteria andSsDayOfWeekBetween(Integer value1, Integer value2) {
            addCriterion("ss_day_of_week between", value1, value2, "ssDayOfWeek");
            return (Criteria) this;
        }

        public Criteria andSsDayOfWeekNotBetween(Integer value1, Integer value2) {
            addCriterion("ss_day_of_week not between", value1, value2, "ssDayOfWeek");
            return (Criteria) this;
        }

        public Criteria andSsEndTimeIsNull() {
            addCriterion("ss_end_time is null");
            return (Criteria) this;
        }

        public Criteria andSsEndTimeIsNotNull() {
            addCriterion("ss_end_time is not null");
            return (Criteria) this;
        }

        public Criteria andSsEndTimeEqualTo(Integer value) {
            addCriterion("ss_end_time =", value, "ssEndTime");
            return (Criteria) this;
        }

        public Criteria andSsEndTimeNotEqualTo(Integer value) {
            addCriterion("ss_end_time <>", value, "ssEndTime");
            return (Criteria) this;
        }

        public Criteria andSsEndTimeGreaterThan(Integer value) {
            addCriterion("ss_end_time >", value, "ssEndTime");
            return (Criteria) this;
        }

        public Criteria andSsEndTimeGreaterThanOrEqualTo(Integer value) {
            addCriterion("ss_end_time >=", value, "ssEndTime");
            return (Criteria) this;
        }

        public Criteria andSsEndTimeLessThan(Integer value) {
            addCriterion("ss_end_time <", value, "ssEndTime");
            return (Criteria) this;
        }

        public Criteria andSsEndTimeLessThanOrEqualTo(Integer value) {
            addCriterion("ss_end_time <=", value, "ssEndTime");
            return (Criteria) this;
        }

        public Criteria andSsEndTimeIn(List<Integer> values) {
            addCriterion("ss_end_time in", values, "ssEndTime");
            return (Criteria) this;
        }

        public Criteria andSsEndTimeNotIn(List<Integer> values) {
            addCriterion("ss_end_time not in", values, "ssEndTime");
            return (Criteria) this;
        }

        public Criteria andSsEndTimeBetween(Integer value1, Integer value2) {
            addCriterion("ss_end_time between", value1, value2, "ssEndTime");
            return (Criteria) this;
        }

        public Criteria andSsEndTimeNotBetween(Integer value1, Integer value2) {
            addCriterion("ss_end_time not between", value1, value2, "ssEndTime");
            return (Criteria) this;
        }

        public Criteria andSsEndWeekIsNull() {
            addCriterion("ss_end_week is null");
            return (Criteria) this;
        }

        public Criteria andSsEndWeekIsNotNull() {
            addCriterion("ss_end_week is not null");
            return (Criteria) this;
        }

        public Criteria andSsEndWeekEqualTo(Integer value) {
            addCriterion("ss_end_week =", value, "ssEndWeek");
            return (Criteria) this;
        }

        public Criteria andSsEndWeekNotEqualTo(Integer value) {
            addCriterion("ss_end_week <>", value, "ssEndWeek");
            return (Criteria) this;
        }

        public Criteria andSsEndWeekGreaterThan(Integer value) {
            addCriterion("ss_end_week >", value, "ssEndWeek");
            return (Criteria) this;
        }

        public Criteria andSsEndWeekGreaterThanOrEqualTo(Integer value) {
            addCriterion("ss_end_week >=", value, "ssEndWeek");
            return (Criteria) this;
        }

        public Criteria andSsEndWeekLessThan(Integer value) {
            addCriterion("ss_end_week <", value, "ssEndWeek");
            return (Criteria) this;
        }

        public Criteria andSsEndWeekLessThanOrEqualTo(Integer value) {
            addCriterion("ss_end_week <=", value, "ssEndWeek");
            return (Criteria) this;
        }

        public Criteria andSsEndWeekIn(List<Integer> values) {
            addCriterion("ss_end_week in", values, "ssEndWeek");
            return (Criteria) this;
        }

        public Criteria andSsEndWeekNotIn(List<Integer> values) {
            addCriterion("ss_end_week not in", values, "ssEndWeek");
            return (Criteria) this;
        }

        public Criteria andSsEndWeekBetween(Integer value1, Integer value2) {
            addCriterion("ss_end_week between", value1, value2, "ssEndWeek");
            return (Criteria) this;
        }

        public Criteria andSsEndWeekNotBetween(Integer value1, Integer value2) {
            addCriterion("ss_end_week not between", value1, value2, "ssEndWeek");
            return (Criteria) this;
        }

        public Criteria andSsFortnightIsNull() {
            addCriterion("ss_fortnight is null");
            return (Criteria) this;
        }

        public Criteria andSsFortnightIsNotNull() {
            addCriterion("ss_fortnight is not null");
            return (Criteria) this;
        }

        public Criteria andSsFortnightEqualTo(Integer value) {
            addCriterion("ss_fortnight =", value, "ssFortnight");
            return (Criteria) this;
        }

        public Criteria andSsFortnightNotEqualTo(Integer value) {
            addCriterion("ss_fortnight <>", value, "ssFortnight");
            return (Criteria) this;
        }

        public Criteria andSsFortnightGreaterThan(Integer value) {
            addCriterion("ss_fortnight >", value, "ssFortnight");
            return (Criteria) this;
        }

        public Criteria andSsFortnightGreaterThanOrEqualTo(Integer value) {
            addCriterion("ss_fortnight >=", value, "ssFortnight");
            return (Criteria) this;
        }

        public Criteria andSsFortnightLessThan(Integer value) {
            addCriterion("ss_fortnight <", value, "ssFortnight");
            return (Criteria) this;
        }

        public Criteria andSsFortnightLessThanOrEqualTo(Integer value) {
            addCriterion("ss_fortnight <=", value, "ssFortnight");
            return (Criteria) this;
        }

        public Criteria andSsFortnightIn(List<Integer> values) {
            addCriterion("ss_fortnight in", values, "ssFortnight");
            return (Criteria) this;
        }

        public Criteria andSsFortnightNotIn(List<Integer> values) {
            addCriterion("ss_fortnight not in", values, "ssFortnight");
            return (Criteria) this;
        }

        public Criteria andSsFortnightBetween(Integer value1, Integer value2) {
            addCriterion("ss_fortnight between", value1, value2, "ssFortnight");
            return (Criteria) this;
        }

        public Criteria andSsFortnightNotBetween(Integer value1, Integer value2) {
            addCriterion("ss_fortnight not between", value1, value2, "ssFortnight");
            return (Criteria) this;
        }

        public Criteria andSsStartTimeIsNull() {
            addCriterion("ss_start_time is null");
            return (Criteria) this;
        }

        public Criteria andSsStartTimeIsNotNull() {
            addCriterion("ss_start_time is not null");
            return (Criteria) this;
        }

        public Criteria andSsStartTimeEqualTo(Integer value) {
            addCriterion("ss_start_time =", value, "ssStartTime");
            return (Criteria) this;
        }

        public Criteria andSsStartTimeNotEqualTo(Integer value) {
            addCriterion("ss_start_time <>", value, "ssStartTime");
            return (Criteria) this;
        }

        public Criteria andSsStartTimeGreaterThan(Integer value) {
            addCriterion("ss_start_time >", value, "ssStartTime");
            return (Criteria) this;
        }

        public Criteria andSsStartTimeGreaterThanOrEqualTo(Integer value) {
            addCriterion("ss_start_time >=", value, "ssStartTime");
            return (Criteria) this;
        }

        public Criteria andSsStartTimeLessThan(Integer value) {
            addCriterion("ss_start_time <", value, "ssStartTime");
            return (Criteria) this;
        }

        public Criteria andSsStartTimeLessThanOrEqualTo(Integer value) {
            addCriterion("ss_start_time <=", value, "ssStartTime");
            return (Criteria) this;
        }

        public Criteria andSsStartTimeIn(List<Integer> values) {
            addCriterion("ss_start_time in", values, "ssStartTime");
            return (Criteria) this;
        }

        public Criteria andSsStartTimeNotIn(List<Integer> values) {
            addCriterion("ss_start_time not in", values, "ssStartTime");
            return (Criteria) this;
        }

        public Criteria andSsStartTimeBetween(Integer value1, Integer value2) {
            addCriterion("ss_start_time between", value1, value2, "ssStartTime");
            return (Criteria) this;
        }

        public Criteria andSsStartTimeNotBetween(Integer value1, Integer value2) {
            addCriterion("ss_start_time not between", value1, value2, "ssStartTime");
            return (Criteria) this;
        }

        public Criteria andSsStartWeekIsNull() {
            addCriterion("ss_start_week is null");
            return (Criteria) this;
        }

        public Criteria andSsStartWeekIsNotNull() {
            addCriterion("ss_start_week is not null");
            return (Criteria) this;
        }

        public Criteria andSsStartWeekEqualTo(Integer value) {
            addCriterion("ss_start_week =", value, "ssStartWeek");
            return (Criteria) this;
        }

        public Criteria andSsStartWeekNotEqualTo(Integer value) {
            addCriterion("ss_start_week <>", value, "ssStartWeek");
            return (Criteria) this;
        }

        public Criteria andSsStartWeekGreaterThan(Integer value) {
            addCriterion("ss_start_week >", value, "ssStartWeek");
            return (Criteria) this;
        }

        public Criteria andSsStartWeekGreaterThanOrEqualTo(Integer value) {
            addCriterion("ss_start_week >=", value, "ssStartWeek");
            return (Criteria) this;
        }

        public Criteria andSsStartWeekLessThan(Integer value) {
            addCriterion("ss_start_week <", value, "ssStartWeek");
            return (Criteria) this;
        }

        public Criteria andSsStartWeekLessThanOrEqualTo(Integer value) {
            addCriterion("ss_start_week <=", value, "ssStartWeek");
            return (Criteria) this;
        }

        public Criteria andSsStartWeekIn(List<Integer> values) {
            addCriterion("ss_start_week in", values, "ssStartWeek");
            return (Criteria) this;
        }

        public Criteria andSsStartWeekNotIn(List<Integer> values) {
            addCriterion("ss_start_week not in", values, "ssStartWeek");
            return (Criteria) this;
        }

        public Criteria andSsStartWeekBetween(Integer value1, Integer value2) {
            addCriterion("ss_start_week between", value1, value2, "ssStartWeek");
            return (Criteria) this;
        }

        public Criteria andSsStartWeekNotBetween(Integer value1, Integer value2) {
            addCriterion("ss_start_week not between", value1, value2, "ssStartWeek");
            return (Criteria) this;
        }

        public Criteria andSsYearEtTermIsNull() {
            addCriterion("ss_year_et_term is null");
            return (Criteria) this;
        }

        public Criteria andSsYearEtTermIsNotNull() {
            addCriterion("ss_year_et_term is not null");
            return (Criteria) this;
        }

        public Criteria andSsYearEtTermEqualTo(String value) {
            addCriterion("ss_year_et_term =", value, "ssYearEtTerm");
            return (Criteria) this;
        }

        public Criteria andSsYearEtTermNotEqualTo(String value) {
            addCriterion("ss_year_et_term <>", value, "ssYearEtTerm");
            return (Criteria) this;
        }

        public Criteria andSsYearEtTermGreaterThan(String value) {
            addCriterion("ss_year_et_term >", value, "ssYearEtTerm");
            return (Criteria) this;
        }

        public Criteria andSsYearEtTermGreaterThanOrEqualTo(String value) {
            addCriterion("ss_year_et_term >=", value, "ssYearEtTerm");
            return (Criteria) this;
        }

        public Criteria andSsYearEtTermLessThan(String value) {
            addCriterion("ss_year_et_term <", value, "ssYearEtTerm");
            return (Criteria) this;
        }

        public Criteria andSsYearEtTermLessThanOrEqualTo(String value) {
            addCriterion("ss_year_et_term <=", value, "ssYearEtTerm");
            return (Criteria) this;
        }

        public Criteria andSsYearEtTermLike(String value) {
            addCriterion("ss_year_et_term like", value, "ssYearEtTerm");
            return (Criteria) this;
        }

        public Criteria andSsYearEtTermNotLike(String value) {
            addCriterion("ss_year_et_term not like", value, "ssYearEtTerm");
            return (Criteria) this;
        }

        public Criteria andSsYearEtTermIn(List<String> values) {
            addCriterion("ss_year_et_term in", values, "ssYearEtTerm");
            return (Criteria) this;
        }

        public Criteria andSsYearEtTermNotIn(List<String> values) {
            addCriterion("ss_year_et_term not in", values, "ssYearEtTerm");
            return (Criteria) this;
        }

        public Criteria andSsYearEtTermBetween(String value1, String value2) {
            addCriterion("ss_year_et_term between", value1, value2, "ssYearEtTerm");
            return (Criteria) this;
        }

        public Criteria andSsYearEtTermNotBetween(String value1, String value2) {
            addCriterion("ss_year_et_term not between", value1, value2, "ssYearEtTerm");
            return (Criteria) this;
        }

        public Criteria andScIdIsNull() {
            addCriterion("sc_id is null");
            return (Criteria) this;
        }

        public Criteria andScIdIsNotNull() {
            addCriterion("sc_id is not null");
            return (Criteria) this;
        }

        public Criteria andScIdEqualTo(String value) {
            addCriterion("sc_id =", value, "scId");
            return (Criteria) this;
        }

        public Criteria andScIdNotEqualTo(String value) {
            addCriterion("sc_id <>", value, "scId");
            return (Criteria) this;
        }

        public Criteria andScIdGreaterThan(String value) {
            addCriterion("sc_id >", value, "scId");
            return (Criteria) this;
        }

        public Criteria andScIdGreaterThanOrEqualTo(String value) {
            addCriterion("sc_id >=", value, "scId");
            return (Criteria) this;
        }

        public Criteria andScIdLessThan(String value) {
            addCriterion("sc_id <", value, "scId");
            return (Criteria) this;
        }

        public Criteria andScIdLessThanOrEqualTo(String value) {
            addCriterion("sc_id <=", value, "scId");
            return (Criteria) this;
        }

        public Criteria andScIdLike(String value) {
            addCriterion("sc_id like", value, "scId");
            return (Criteria) this;
        }

        public Criteria andScIdNotLike(String value) {
            addCriterion("sc_id not like", value, "scId");
            return (Criteria) this;
        }

        public Criteria andScIdIn(List<String> values) {
            addCriterion("sc_id in", values, "scId");
            return (Criteria) this;
        }

        public Criteria andScIdNotIn(List<String> values) {
            addCriterion("sc_id not in", values, "scId");
            return (Criteria) this;
        }

        public Criteria andScIdBetween(String value1, String value2) {
            addCriterion("sc_id between", value1, value2, "scId");
            return (Criteria) this;
        }

        public Criteria andScIdNotBetween(String value1, String value2) {
            addCriterion("sc_id not between", value1, value2, "scId");
            return (Criteria) this;
        }

        public Criteria andSsSuspensionIsNull() {
            addCriterion("ss_suspension is null");
            return (Criteria) this;
        }

        public Criteria andSsSuspensionIsNotNull() {
            addCriterion("ss_suspension is not null");
            return (Criteria) this;
        }

        public Criteria andSsSuspensionEqualTo(String value) {
            addCriterion("ss_suspension =", value, "ssSuspension");
            return (Criteria) this;
        }

        public Criteria andSsSuspensionNotEqualTo(String value) {
            addCriterion("ss_suspension <>", value, "ssSuspension");
            return (Criteria) this;
        }

        public Criteria andSsSuspensionGreaterThan(String value) {
            addCriterion("ss_suspension >", value, "ssSuspension");
            return (Criteria) this;
        }

        public Criteria andSsSuspensionGreaterThanOrEqualTo(String value) {
            addCriterion("ss_suspension >=", value, "ssSuspension");
            return (Criteria) this;
        }

        public Criteria andSsSuspensionLessThan(String value) {
            addCriterion("ss_suspension <", value, "ssSuspension");
            return (Criteria) this;
        }

        public Criteria andSsSuspensionLessThanOrEqualTo(String value) {
            addCriterion("ss_suspension <=", value, "ssSuspension");
            return (Criteria) this;
        }

        public Criteria andSsSuspensionLike(String value) {
            addCriterion("ss_suspension like", value, "ssSuspension");
            return (Criteria) this;
        }

        public Criteria andSsSuspensionNotLike(String value) {
            addCriterion("ss_suspension not like", value, "ssSuspension");
            return (Criteria) this;
        }

        public Criteria andSsSuspensionIn(List<String> values) {
            addCriterion("ss_suspension in", values, "ssSuspension");
            return (Criteria) this;
        }

        public Criteria andSsSuspensionNotIn(List<String> values) {
            addCriterion("ss_suspension not in", values, "ssSuspension");
            return (Criteria) this;
        }

        public Criteria andSsSuspensionBetween(String value1, String value2) {
            addCriterion("ss_suspension between", value1, value2, "ssSuspension");
            return (Criteria) this;
        }

        public Criteria andSsSuspensionNotBetween(String value1, String value2) {
            addCriterion("ss_suspension not between", value1, value2, "ssSuspension");
            return (Criteria) this;
        }

        public Criteria andSsRoomIsNull() {
            addCriterion("ss_room is null");
            return (Criteria) this;
        }

        public Criteria andSsRoomIsNotNull() {
            addCriterion("ss_room is not null");
            return (Criteria) this;
        }

        public Criteria andSsRoomEqualTo(String value) {
            addCriterion("ss_room =", value, "ssRoom");
            return (Criteria) this;
        }

        public Criteria andSsRoomNotEqualTo(String value) {
            addCriterion("ss_room <>", value, "ssRoom");
            return (Criteria) this;
        }

        public Criteria andSsRoomGreaterThan(String value) {
            addCriterion("ss_room >", value, "ssRoom");
            return (Criteria) this;
        }

        public Criteria andSsRoomGreaterThanOrEqualTo(String value) {
            addCriterion("ss_room >=", value, "ssRoom");
            return (Criteria) this;
        }

        public Criteria andSsRoomLessThan(String value) {
            addCriterion("ss_room <", value, "ssRoom");
            return (Criteria) this;
        }

        public Criteria andSsRoomLessThanOrEqualTo(String value) {
            addCriterion("ss_room <=", value, "ssRoom");
            return (Criteria) this;
        }

        public Criteria andSsRoomLike(String value) {
            addCriterion("ss_room like", value, "ssRoom");
            return (Criteria) this;
        }

        public Criteria andSsRoomNotLike(String value) {
            addCriterion("ss_room not like", value, "ssRoom");
            return (Criteria) this;
        }

        public Criteria andSsRoomIn(List<String> values) {
            addCriterion("ss_room in", values, "ssRoom");
            return (Criteria) this;
        }

        public Criteria andSsRoomNotIn(List<String> values) {
            addCriterion("ss_room not in", values, "ssRoom");
            return (Criteria) this;
        }

        public Criteria andSsRoomBetween(String value1, String value2) {
            addCriterion("ss_room between", value1, value2, "ssRoom");
            return (Criteria) this;
        }

        public Criteria andSsRoomNotBetween(String value1, String value2) {
            addCriterion("ss_room not between", value1, value2, "ssRoom");
            return (Criteria) this;
        }

        public Criteria andSlIdIsNull() {
            addCriterion("sl_id is null");
            return (Criteria) this;
        }

        public Criteria andSlIdIsNotNull() {
            addCriterion("sl_id is not null");
            return (Criteria) this;
        }

        public Criteria andSlIdEqualTo(Integer value) {
            addCriterion("sl_id =", value, "slId");
            return (Criteria) this;
        }

        public Criteria andSlIdNotEqualTo(Integer value) {
            addCriterion("sl_id <>", value, "slId");
            return (Criteria) this;
        }

        public Criteria andSlIdGreaterThan(Integer value) {
            addCriterion("sl_id >", value, "slId");
            return (Criteria) this;
        }

        public Criteria andSlIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("sl_id >=", value, "slId");
            return (Criteria) this;
        }

        public Criteria andSlIdLessThan(Integer value) {
            addCriterion("sl_id <", value, "slId");
            return (Criteria) this;
        }

        public Criteria andSlIdLessThanOrEqualTo(Integer value) {
            addCriterion("sl_id <=", value, "slId");
            return (Criteria) this;
        }

        public Criteria andSlIdIn(List<Integer> values) {
            addCriterion("sl_id in", values, "slId");
            return (Criteria) this;
        }

        public Criteria andSlIdNotIn(List<Integer> values) {
            addCriterion("sl_id not in", values, "slId");
            return (Criteria) this;
        }

        public Criteria andSlIdBetween(Integer value1, Integer value2) {
            addCriterion("sl_id between", value1, value2, "slId");
            return (Criteria) this;
        }

        public Criteria andSlIdNotBetween(Integer value1, Integer value2) {
            addCriterion("sl_id not between", value1, value2, "slId");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table sis_schedule
     *
     * @mbg.generated do_not_delete_during_merge Wed Sep 19 17:25:34 CST 2018
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table sis_schedule
     *
     * @mbg.generated Wed Sep 19 17:25:34 CST 2018
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}