package team.a9043.sign_in_system.pojo;

import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

import javax.validation.constraints.NotNull;

@ApiModel("督导记录")
public class SisSupervision extends SisSupervisionKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sis_supervision.ssv_actual_num
     *
     * @mbg.generated Mon Aug 27 13:08:41 CST 2018
     */

    @NotNull
    @ApiModelProperty("实际上课人数")
    private Integer ssvActualNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sis_supervision.ssv_mobile_num
     *
     * @mbg.generated Mon Aug 27 13:08:41 CST 2018
     */
    @NotNull
    @ApiModelProperty("玩手机人数")
    private Integer ssvMobileNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sis_supervision.ssv_rec_info
     *
     * @mbg.generated Mon Aug 27 13:08:41 CST 2018
     */
    @NotNull
    @ApiModelProperty(value = "督导详情记录", notes = "长度不超过150字")
    private String ssvRecInfo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sis_supervision.ssv_sleep_num
     *
     * @mbg.generated Mon Aug 27 13:08:41 CST 2018
     */
    @NotNull
    @ApiModelProperty("睡觉人数")
    private Integer ssvSleepNum;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sis_supervision.ssv_actual_num
     *
     * @return the value of sis_supervision.ssv_actual_num
     * @mbg.generated Mon Aug 27 13:08:41 CST 2018
     */
    public Integer getSsvActualNum() {
        return ssvActualNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sis_supervision.ssv_actual_num
     *
     * @param ssvActualNum the value for sis_supervision.ssv_actual_num
     * @mbg.generated Mon Aug 27 13:08:41 CST 2018
     */
    public void setSsvActualNum(Integer ssvActualNum) {
        this.ssvActualNum = ssvActualNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sis_supervision.ssv_mobile_num
     *
     * @return the value of sis_supervision.ssv_mobile_num
     * @mbg.generated Mon Aug 27 13:08:41 CST 2018
     */
    public Integer getSsvMobileNum() {
        return ssvMobileNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sis_supervision.ssv_mobile_num
     *
     * @param ssvMobileNum the value for sis_supervision.ssv_mobile_num
     * @mbg.generated Mon Aug 27 13:08:41 CST 2018
     */
    public void setSsvMobileNum(Integer ssvMobileNum) {
        this.ssvMobileNum = ssvMobileNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sis_supervision.ssv_rec_info
     *
     * @return the value of sis_supervision.ssv_rec_info
     * @mbg.generated Mon Aug 27 13:08:41 CST 2018
     */
    public String getSsvRecInfo() {
        return ssvRecInfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sis_supervision.ssv_rec_info
     *
     * @param ssvRecInfo the value for sis_supervision.ssv_rec_info
     * @mbg.generated Mon Aug 27 13:08:41 CST 2018
     */
    public void setSsvRecInfo(String ssvRecInfo) {
        this.ssvRecInfo = ssvRecInfo == null ? null : ssvRecInfo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sis_supervision.ssv_sleep_num
     *
     * @return the value of sis_supervision.ssv_sleep_num
     * @mbg.generated Mon Aug 27 13:08:41 CST 2018
     */
    public Integer getSsvSleepNum() {
        return ssvSleepNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sis_supervision.ssv_sleep_num
     *
     * @param ssvSleepNum the value for sis_supervision.ssv_sleep_num
     * @mbg.generated Mon Aug 27 13:08:41 CST 2018
     */
    public void setSsvSleepNum(Integer ssvSleepNum) {
        this.ssvSleepNum = ssvSleepNum;
    }
}