package team.a9043.sign_in_system.pojo;

import java.util.ArrayList;
import java.util.List;

public class SisUserExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sis_user
     *
     * @mbg.generated Mon Aug 27 13:08:41 CST 2018
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sis_user
     *
     * @mbg.generated Mon Aug 27 13:08:41 CST 2018
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sis_user
     *
     * @mbg.generated Mon Aug 27 13:08:41 CST 2018
     */
    protected List<Criteria> oredCriteria;

    private Boolean ordByLackNum;

    private Boolean orderByCozLackNum;

    public Boolean getOrderByCozLackNum() {
        return orderByCozLackNum;
    }

    public void setOrderByCozLackNum(Boolean orderByCozLackNum) {
        this.orderByCozLackNum = orderByCozLackNum;
    }

    public Boolean getOrdByLackNum() {
        return ordByLackNum;
    }

    public void setOrdByLackNum(Boolean ordByLackNum) {
        this.ordByLackNum = ordByLackNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sis_user
     *
     * @mbg.generated Mon Aug 27 13:08:41 CST 2018
     */
    public SisUserExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sis_user
     *
     * @mbg.generated Mon Aug 27 13:08:41 CST 2018
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sis_user
     *
     * @mbg.generated Mon Aug 27 13:08:41 CST 2018
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sis_user
     *
     * @mbg.generated Mon Aug 27 13:08:41 CST 2018
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sis_user
     *
     * @mbg.generated Mon Aug 27 13:08:41 CST 2018
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sis_user
     *
     * @mbg.generated Mon Aug 27 13:08:41 CST 2018
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sis_user
     *
     * @mbg.generated Mon Aug 27 13:08:41 CST 2018
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sis_user
     *
     * @mbg.generated Mon Aug 27 13:08:41 CST 2018
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sis_user
     *
     * @mbg.generated Mon Aug 27 13:08:41 CST 2018
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sis_user
     *
     * @mbg.generated Mon Aug 27 13:08:41 CST 2018
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sis_user
     *
     * @mbg.generated Mon Aug 27 13:08:41 CST 2018
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table sis_user
     *
     * @mbg.generated Mon Aug 27 13:08:41 CST 2018
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andSuIdIsNull() {
            addCriterion("sis_user.su_id is null");
            return (Criteria) this;
        }

        public Criteria andSuIdIsNotNull() {
            addCriterion("sis_user.su_id is not null");
            return (Criteria) this;
        }

        public Criteria andSuIdEqualTo(String value) {
            addCriterion("sis_user.su_id =", value, "suId");
            return (Criteria) this;
        }

        public Criteria andSuIdNotEqualTo(String value) {
            addCriterion("sis_user.su_id <>", value, "suId");
            return (Criteria) this;
        }

        public Criteria andSuIdGreaterThan(String value) {
            addCriterion("sis_user.su_id >", value, "suId");
            return (Criteria) this;
        }

        public Criteria andSuIdGreaterThanOrEqualTo(String value) {
            addCriterion("sis_user.su_id >=", value, "suId");
            return (Criteria) this;
        }

        public Criteria andSuIdLessThan(String value) {
            addCriterion("sis_user.su_id <", value, "suId");
            return (Criteria) this;
        }

        public Criteria andSuIdLessThanOrEqualTo(String value) {
            addCriterion("sis_user.su_id <=", value, "suId");
            return (Criteria) this;
        }

        public Criteria andSuIdLike(String value) {
            addCriterion("sis_user.su_id like", value, "suId");
            return (Criteria) this;
        }

        public Criteria andSuIdNotLike(String value) {
            addCriterion("sis_user.su_id not like", value, "suId");
            return (Criteria) this;
        }

        public Criteria andSuIdIn(List<String> values) {
            addCriterion("sis_user.su_id in", values, "suId");
            return (Criteria) this;
        }

        public Criteria andSuIdNotIn(List<String> values) {
            addCriterion("sis_user.su_id not in", values, "suId");
            return (Criteria) this;
        }

        public Criteria andSuIdBetween(String value1, String value2) {
            addCriterion("sis_user.su_id between", value1, value2, "suId");
            return (Criteria) this;
        }

        public Criteria andSuIdNotBetween(String value1, String value2) {
            addCriterion("sis_user.su_id not between", value1, value2, "suId");
            return (Criteria) this;
        }

        public Criteria andSuAuthoritiesStrIsNull() {
            addCriterion("su_authorities_str is null");
            return (Criteria) this;
        }

        public Criteria andSuAuthoritiesStrIsNotNull() {
            addCriterion("su_authorities_str is not null");
            return (Criteria) this;
        }

        public Criteria andSuAuthoritiesStrEqualTo(String value) {
            addCriterion("su_authorities_str =", value, "suAuthoritiesStr");
            return (Criteria) this;
        }

        public Criteria andSuAuthoritiesStrNotEqualTo(String value) {
            addCriterion("su_authorities_str <>", value, "suAuthoritiesStr");
            return (Criteria) this;
        }

        public Criteria andSuAuthoritiesStrGreaterThan(String value) {
            addCriterion("su_authorities_str >", value, "suAuthoritiesStr");
            return (Criteria) this;
        }

        public Criteria andSuAuthoritiesStrGreaterThanOrEqualTo(String value) {
            addCriterion("su_authorities_str >=", value, "suAuthoritiesStr");
            return (Criteria) this;
        }

        public Criteria andSuAuthoritiesStrLessThan(String value) {
            addCriterion("su_authorities_str <", value, "suAuthoritiesStr");
            return (Criteria) this;
        }

        public Criteria andSuAuthoritiesStrLessThanOrEqualTo(String value) {
            addCriterion("su_authorities_str <=", value, "suAuthoritiesStr");
            return (Criteria) this;
        }

        public Criteria andSuAuthoritiesStrLike(String value) {
            addCriterion("su_authorities_str like", value, "suAuthoritiesStr");
            return (Criteria) this;
        }

        public Criteria andSuAuthoritiesStrNotLike(String value) {
            addCriterion("su_authorities_str not like", value, "suAuthoritiesStr");
            return (Criteria) this;
        }

        public Criteria andSuAuthoritiesStrIn(List<String> values) {
            addCriterion("su_authorities_str in", values, "suAuthoritiesStr");
            return (Criteria) this;
        }

        public Criteria andSuAuthoritiesStrNotIn(List<String> values) {
            addCriterion("su_authorities_str not in", values, "suAuthoritiesStr");
            return (Criteria) this;
        }

        public Criteria andSuAuthoritiesStrBetween(String value1, String value2) {
            addCriterion("su_authorities_str between", value1, value2, "suAuthoritiesStr");
            return (Criteria) this;
        }

        public Criteria andSuAuthoritiesStrNotBetween(String value1, String value2) {
            addCriterion("su_authorities_str not between", value1, value2, "suAuthoritiesStr");
            return (Criteria) this;
        }

        public Criteria andSuNameIsNull() {
            addCriterion("su_name is null");
            return (Criteria) this;
        }

        public Criteria andSuNameIsNotNull() {
            addCriterion("su_name is not null");
            return (Criteria) this;
        }

        public Criteria andSuNameEqualTo(String value) {
            addCriterion("su_name =", value, "suName");
            return (Criteria) this;
        }

        public Criteria andSuNameNotEqualTo(String value) {
            addCriterion("su_name <>", value, "suName");
            return (Criteria) this;
        }

        public Criteria andSuNameGreaterThan(String value) {
            addCriterion("su_name >", value, "suName");
            return (Criteria) this;
        }

        public Criteria andSuNameGreaterThanOrEqualTo(String value) {
            addCriterion("su_name >=", value, "suName");
            return (Criteria) this;
        }

        public Criteria andSuNameLessThan(String value) {
            addCriterion("su_name <", value, "suName");
            return (Criteria) this;
        }

        public Criteria andSuNameLessThanOrEqualTo(String value) {
            addCriterion("su_name <=", value, "suName");
            return (Criteria) this;
        }

        public Criteria andSuNameLike(String value) {
            addCriterion("su_name like", value, "suName");
            return (Criteria) this;
        }

        public Criteria andSuNameNotLike(String value) {
            addCriterion("su_name not like", value, "suName");
            return (Criteria) this;
        }

        public Criteria andSuNameIn(List<String> values) {
            addCriterion("su_name in", values, "suName");
            return (Criteria) this;
        }

        public Criteria andSuNameNotIn(List<String> values) {
            addCriterion("su_name not in", values, "suName");
            return (Criteria) this;
        }

        public Criteria andSuNameBetween(String value1, String value2) {
            addCriterion("su_name between", value1, value2, "suName");
            return (Criteria) this;
        }

        public Criteria andSuNameNotBetween(String value1, String value2) {
            addCriterion("su_name not between", value1, value2, "suName");
            return (Criteria) this;
        }

        public Criteria andSuOpenidIsNull() {
            addCriterion("su_openid is null");
            return (Criteria) this;
        }

        public Criteria andSuOpenidIsNotNull() {
            addCriterion("su_openid is not null");
            return (Criteria) this;
        }

        public Criteria andSuOpenidEqualTo(String value) {
            addCriterion("su_openid =", value, "suOpenid");
            return (Criteria) this;
        }

        public Criteria andSuOpenidNotEqualTo(String value) {
            addCriterion("su_openid <>", value, "suOpenid");
            return (Criteria) this;
        }

        public Criteria andSuOpenidGreaterThan(String value) {
            addCriterion("su_openid >", value, "suOpenid");
            return (Criteria) this;
        }

        public Criteria andSuOpenidGreaterThanOrEqualTo(String value) {
            addCriterion("su_openid >=", value, "suOpenid");
            return (Criteria) this;
        }

        public Criteria andSuOpenidLessThan(String value) {
            addCriterion("su_openid <", value, "suOpenid");
            return (Criteria) this;
        }

        public Criteria andSuOpenidLessThanOrEqualTo(String value) {
            addCriterion("su_openid <=", value, "suOpenid");
            return (Criteria) this;
        }

        public Criteria andSuOpenidLike(String value) {
            addCriterion("su_openid like", value, "suOpenid");
            return (Criteria) this;
        }

        public Criteria andSuOpenidNotLike(String value) {
            addCriterion("su_openid not like", value, "suOpenid");
            return (Criteria) this;
        }

        public Criteria andSuOpenidIn(List<String> values) {
            addCriterion("su_openid in", values, "suOpenid");
            return (Criteria) this;
        }

        public Criteria andSuOpenidNotIn(List<String> values) {
            addCriterion("su_openid not in", values, "suOpenid");
            return (Criteria) this;
        }

        public Criteria andSuOpenidBetween(String value1, String value2) {
            addCriterion("su_openid between", value1, value2, "suOpenid");
            return (Criteria) this;
        }

        public Criteria andSuOpenidNotBetween(String value1, String value2) {
            addCriterion("su_openid not between", value1, value2, "suOpenid");
            return (Criteria) this;
        }

        public Criteria andSuPasswordIsNull() {
            addCriterion("su_password is null");
            return (Criteria) this;
        }

        public Criteria andSuPasswordIsNotNull() {
            addCriterion("su_password is not null");
            return (Criteria) this;
        }

        public Criteria andSuPasswordEqualTo(String value) {
            addCriterion("su_password =", value, "suPassword");
            return (Criteria) this;
        }

        public Criteria andSuPasswordNotEqualTo(String value) {
            addCriterion("su_password <>", value, "suPassword");
            return (Criteria) this;
        }

        public Criteria andSuPasswordGreaterThan(String value) {
            addCriterion("su_password >", value, "suPassword");
            return (Criteria) this;
        }

        public Criteria andSuPasswordGreaterThanOrEqualTo(String value) {
            addCriterion("su_password >=", value, "suPassword");
            return (Criteria) this;
        }

        public Criteria andSuPasswordLessThan(String value) {
            addCriterion("su_password <", value, "suPassword");
            return (Criteria) this;
        }

        public Criteria andSuPasswordLessThanOrEqualTo(String value) {
            addCriterion("su_password <=", value, "suPassword");
            return (Criteria) this;
        }

        public Criteria andSuPasswordLike(String value) {
            addCriterion("su_password like", value, "suPassword");
            return (Criteria) this;
        }

        public Criteria andSuPasswordNotLike(String value) {
            addCriterion("su_password not like", value, "suPassword");
            return (Criteria) this;
        }

        public Criteria andSuPasswordIn(List<String> values) {
            addCriterion("su_password in", values, "suPassword");
            return (Criteria) this;
        }

        public Criteria andSuPasswordNotIn(List<String> values) {
            addCriterion("su_password not in", values, "suPassword");
            return (Criteria) this;
        }

        public Criteria andSuPasswordBetween(String value1, String value2) {
            addCriterion("su_password between", value1, value2, "suPassword");
            return (Criteria) this;
        }

        public Criteria andSuPasswordNotBetween(String value1, String value2) {
            addCriterion("su_password not between", value1, value2, "suPassword");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table sis_user
     *
     * @mbg.generated do_not_delete_during_merge Mon Aug 27 13:08:41 CST 2018
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table sis_user
     *
     * @mbg.generated Mon Aug 27 13:08:41 CST 2018
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}